<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="ezr32.ezr32lg.msc" label="MSC" name="MSC" description="" version="ezr">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="MSC.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="MSC.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="MSC.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="MSC.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="MSC.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
    </properties>
    <propertyCategories>
      <category label="MSC">
        <subCategory label="">
          <propertyRef refId="MSC.usedbysdk.BOOL"/>
          <propertyRef refId="MSC.hiddenbysdk.BOOL"/>
          <propertyRef refId="MSC.showadvanced.BOOL"/>
          <propertyRef refId="MSC.forceenable.BOOL"/>
          <propertyRef refId="MSC.owner.STRING"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
