<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="ezr32.ezr32hg.usartrf1" label="USARTRF1" name="USARTRF1" description="" version="ezr">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="USARTRF.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="USARTRF.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="USARTRF.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="USARTRF.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="USARTRF.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <stringProperty label="Custom name" id="USARTRF.customname.STRING" defaultValue="" hidden="false" readonly="false"/>
    </properties>
    <propertyCategories>
      <category label="USARTRF1">
        <subCategory label="">
          <propertyRef refId="USARTRF.usedbysdk.BOOL"/>
          <propertyRef refId="USARTRF.hiddenbysdk.BOOL"/>
          <propertyRef refId="USARTRF.showadvanced.BOOL"/>
          <propertyRef refId="USARTRF.forceenable.BOOL"/>
          <propertyRef refId="USARTRF.owner.STRING"/>
          <propertyRef refId="USARTRF.customname.STRING"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
