<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efm32.efm32hg.prs" label="PRS" name="PRS" description="" version="efm">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="PRS.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="PRS.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="PRS.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="PRS.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="PRS.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <stringProperty label="Custom name" id="PRS.custom_name_CH0.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH0_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="PCNT0" value="PCNT0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch0_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH0.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH1.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH1_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="PCNT0" value="PCNT0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch1_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH1.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH2.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH2_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="PCNT0" value="PCNT0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch2_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH2.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH3.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH3_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="PCNT0" value="PCNT0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch3_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH3.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH4.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH4_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="PCNT0" value="PCNT0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch4_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <stringProperty label="Custom name" id="PRS.custom_name_CH5.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH5_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="PCNT0" value="PCNT0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_IRTX" value="USART1_IRTX"/>
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch5_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
    </properties>
    <propertyCategories>
      <category label="PRS">
        <subCategory label="">
          <propertyRef refId="PRS.usedbysdk.BOOL"/>
          <propertyRef refId="PRS.hiddenbysdk.BOOL"/>
          <propertyRef refId="PRS.showadvanced.BOOL"/>
          <propertyRef refId="PRS.forceenable.BOOL"/>
          <propertyRef refId="PRS.owner.STRING"/>
        </subCategory>
        <subCategory label="CH0 properties">
          <propertyRef refId="PRS.custom_name_CH0.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch0_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH0.PIN"/>
        </subCategory>
        <subCategory label="CH1 properties">
          <propertyRef refId="PRS.custom_name_CH1.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch1_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH1.PIN"/>
        </subCategory>
        <subCategory label="CH2 properties">
          <propertyRef refId="PRS.custom_name_CH2.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch2_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH2.PIN"/>
        </subCategory>
        <subCategory label="CH3 properties">
          <propertyRef refId="PRS.custom_name_CH3.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch3_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH3.PIN"/>
        </subCategory>
        <subCategory label="CH4 properties">
          <propertyRef refId="PRS.custom_name_CH4.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch4_signal_disabled.STRING"/>
        </subCategory>
        <subCategory label="CH5 properties">
          <propertyRef refId="PRS.custom_name_CH5.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch5_signal_disabled.STRING"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
