// This is an autogenerated config file, any changes to this file will be overwritten

#ifndef SLI_PSA_BUILTIN_CONFIG_AUTOGEN_H
#define SLI_PSA_BUILTIN_CONFIG_AUTOGEN_H

/// Do not need this feature - SLC imposed
// #define MBEDTLS_PSA_BUILTIN_KEY_TYPE_AES 1
// #define MBEDTLS_PSA_BUILTIN_ALG_ECB_NO_PADDING 1
// #define MBEDTLS_PSA_BUILTIN_ALG_CMAC 1
// #define MBEDTLS_PSA_BUILTIN_ALG_PBKDF2_AES_CMAC_PRF_128 1

#endif // SLI_PSA_BUILTIN_CONFIG_AUTOGEN_H
