<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efm32.efm32zg.hdlc" label="HDLC" name="HDLC" description="" version="efm">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="HDLC.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="HDLC.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="HDLC.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="HDLC.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="HDLC.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
    </properties>
    <propertyCategories>
      <category label="HDLC">
        <subCategory label="">
          <propertyRef refId="HDLC.usedbysdk.BOOL"/>
          <propertyRef refId="HDLC.hiddenbysdk.BOOL"/>
          <propertyRef refId="HDLC.showadvanced.BOOL"/>
          <propertyRef refId="HDLC.forceenable.BOOL"/>
          <propertyRef refId="HDLC.owner.STRING"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
