<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="ezr32.ezr32lg.prs" label="PRS" name="PRS" description="" version="ezr">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="PRS.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="PRS.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="PRS.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="PRS.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="PRS.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <stringProperty label="Custom name" id="PRS.custom_name_CH0.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH0_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="DAC0" value="DAC0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USARTRF0" value="USARTRF0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="USART2" value="USART2"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="UART0" value="UART0"/>
        <enumValue label="UART1" value="UART1"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="LESENSE" value="LESENSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_DAC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="DAC0_CH0" value="DAC0_CH0"/>
        <enumValue label="DAC0_CH1" value="DAC0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_USARTRF0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USARTRF0_IRTX" value="USARTRF0_IRTX"/>
        <enumValue label="USARTRF0_TXC" value="USARTRF0_TXC"/>
        <enumValue label="USARTRF0_RXDATAV" value="USARTRF0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_USART2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART2_TXC" value="USART2_TXC"/>
        <enumValue label="USART2_RXDATAV" value="USART2_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_UART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART0_TXC" value="UART0_TXC"/>
        <enumValue label="UART0_RXDATAV" value="UART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_UART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART1_TXC" value="UART1_TXC"/>
        <enumValue label="UART1_RXDATAV" value="UART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_OF" value="BURTC_OF"/>
        <enumValue label="BURTC_COMP0" value="BURTC_COMP0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_SCANRES0" value="LESENSE_SCANRES0"/>
        <enumValue label="LESENSE_SCANRES1" value="LESENSE_SCANRES1"/>
        <enumValue label="LESENSE_SCANRES2" value="LESENSE_SCANRES2"/>
        <enumValue label="LESENSE_SCANRES3" value="LESENSE_SCANRES3"/>
        <enumValue label="LESENSE_SCANRES4" value="LESENSE_SCANRES4"/>
        <enumValue label="LESENSE_SCANRES5" value="LESENSE_SCANRES5"/>
        <enumValue label="LESENSE_SCANRES6" value="LESENSE_SCANRES6"/>
        <enumValue label="LESENSE_SCANRES7" value="LESENSE_SCANRES7"/>
        <enumValue label="LESENSE_SCANRES8" value="LESENSE_SCANRES8"/>
        <enumValue label="LESENSE_SCANRES9" value="LESENSE_SCANRES9"/>
        <enumValue label="LESENSE_SCANRES10" value="LESENSE_SCANRES10"/>
        <enumValue label="LESENSE_SCANRES11" value="LESENSE_SCANRES11"/>
        <enumValue label="LESENSE_SCANRES12" value="LESENSE_SCANRES12"/>
        <enumValue label="LESENSE_SCANRES13" value="LESENSE_SCANRES13"/>
        <enumValue label="LESENSE_SCANRES14" value="LESENSE_SCANRES14"/>
        <enumValue label="LESENSE_SCANRES15" value="LESENSE_SCANRES15"/>
        <enumValue label="LESENSE_DEC0" value="LESENSE_DEC0"/>
        <enumValue label="LESENSE_DEC1" value="LESENSE_DEC1"/>
        <enumValue label="LESENSE_DEC2" value="LESENSE_DEC2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch0_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH0.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH1.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH1_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="DAC0" value="DAC0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USARTRF0" value="USARTRF0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="USART2" value="USART2"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="UART0" value="UART0"/>
        <enumValue label="UART1" value="UART1"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="LESENSE" value="LESENSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_DAC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="DAC0_CH0" value="DAC0_CH0"/>
        <enumValue label="DAC0_CH1" value="DAC0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_USARTRF0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USARTRF0_IRTX" value="USARTRF0_IRTX"/>
        <enumValue label="USARTRF0_TXC" value="USARTRF0_TXC"/>
        <enumValue label="USARTRF0_RXDATAV" value="USARTRF0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_USART2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART2_TXC" value="USART2_TXC"/>
        <enumValue label="USART2_RXDATAV" value="USART2_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_UART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART0_TXC" value="UART0_TXC"/>
        <enumValue label="UART0_RXDATAV" value="UART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_UART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART1_TXC" value="UART1_TXC"/>
        <enumValue label="UART1_RXDATAV" value="UART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_OF" value="BURTC_OF"/>
        <enumValue label="BURTC_COMP0" value="BURTC_COMP0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_SCANRES0" value="LESENSE_SCANRES0"/>
        <enumValue label="LESENSE_SCANRES1" value="LESENSE_SCANRES1"/>
        <enumValue label="LESENSE_SCANRES2" value="LESENSE_SCANRES2"/>
        <enumValue label="LESENSE_SCANRES3" value="LESENSE_SCANRES3"/>
        <enumValue label="LESENSE_SCANRES4" value="LESENSE_SCANRES4"/>
        <enumValue label="LESENSE_SCANRES5" value="LESENSE_SCANRES5"/>
        <enumValue label="LESENSE_SCANRES6" value="LESENSE_SCANRES6"/>
        <enumValue label="LESENSE_SCANRES7" value="LESENSE_SCANRES7"/>
        <enumValue label="LESENSE_SCANRES8" value="LESENSE_SCANRES8"/>
        <enumValue label="LESENSE_SCANRES9" value="LESENSE_SCANRES9"/>
        <enumValue label="LESENSE_SCANRES10" value="LESENSE_SCANRES10"/>
        <enumValue label="LESENSE_SCANRES11" value="LESENSE_SCANRES11"/>
        <enumValue label="LESENSE_SCANRES12" value="LESENSE_SCANRES12"/>
        <enumValue label="LESENSE_SCANRES13" value="LESENSE_SCANRES13"/>
        <enumValue label="LESENSE_SCANRES14" value="LESENSE_SCANRES14"/>
        <enumValue label="LESENSE_SCANRES15" value="LESENSE_SCANRES15"/>
        <enumValue label="LESENSE_DEC0" value="LESENSE_DEC0"/>
        <enumValue label="LESENSE_DEC1" value="LESENSE_DEC1"/>
        <enumValue label="LESENSE_DEC2" value="LESENSE_DEC2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch1_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH1.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH2.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH2_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="DAC0" value="DAC0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USARTRF0" value="USARTRF0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="USART2" value="USART2"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="UART0" value="UART0"/>
        <enumValue label="UART1" value="UART1"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="LESENSE" value="LESENSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_DAC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="DAC0_CH0" value="DAC0_CH0"/>
        <enumValue label="DAC0_CH1" value="DAC0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_USARTRF0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USARTRF0_IRTX" value="USARTRF0_IRTX"/>
        <enumValue label="USARTRF0_TXC" value="USARTRF0_TXC"/>
        <enumValue label="USARTRF0_RXDATAV" value="USARTRF0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_USART2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART2_TXC" value="USART2_TXC"/>
        <enumValue label="USART2_RXDATAV" value="USART2_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_UART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART0_TXC" value="UART0_TXC"/>
        <enumValue label="UART0_RXDATAV" value="UART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_UART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART1_TXC" value="UART1_TXC"/>
        <enumValue label="UART1_RXDATAV" value="UART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_OF" value="BURTC_OF"/>
        <enumValue label="BURTC_COMP0" value="BURTC_COMP0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_SCANRES0" value="LESENSE_SCANRES0"/>
        <enumValue label="LESENSE_SCANRES1" value="LESENSE_SCANRES1"/>
        <enumValue label="LESENSE_SCANRES2" value="LESENSE_SCANRES2"/>
        <enumValue label="LESENSE_SCANRES3" value="LESENSE_SCANRES3"/>
        <enumValue label="LESENSE_SCANRES4" value="LESENSE_SCANRES4"/>
        <enumValue label="LESENSE_SCANRES5" value="LESENSE_SCANRES5"/>
        <enumValue label="LESENSE_SCANRES6" value="LESENSE_SCANRES6"/>
        <enumValue label="LESENSE_SCANRES7" value="LESENSE_SCANRES7"/>
        <enumValue label="LESENSE_SCANRES8" value="LESENSE_SCANRES8"/>
        <enumValue label="LESENSE_SCANRES9" value="LESENSE_SCANRES9"/>
        <enumValue label="LESENSE_SCANRES10" value="LESENSE_SCANRES10"/>
        <enumValue label="LESENSE_SCANRES11" value="LESENSE_SCANRES11"/>
        <enumValue label="LESENSE_SCANRES12" value="LESENSE_SCANRES12"/>
        <enumValue label="LESENSE_SCANRES13" value="LESENSE_SCANRES13"/>
        <enumValue label="LESENSE_SCANRES14" value="LESENSE_SCANRES14"/>
        <enumValue label="LESENSE_SCANRES15" value="LESENSE_SCANRES15"/>
        <enumValue label="LESENSE_DEC0" value="LESENSE_DEC0"/>
        <enumValue label="LESENSE_DEC1" value="LESENSE_DEC1"/>
        <enumValue label="LESENSE_DEC2" value="LESENSE_DEC2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch2_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH2.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH3.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH3_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="DAC0" value="DAC0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USARTRF0" value="USARTRF0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="USART2" value="USART2"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="UART0" value="UART0"/>
        <enumValue label="UART1" value="UART1"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="LESENSE" value="LESENSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_DAC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="DAC0_CH0" value="DAC0_CH0"/>
        <enumValue label="DAC0_CH1" value="DAC0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_USARTRF0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USARTRF0_IRTX" value="USARTRF0_IRTX"/>
        <enumValue label="USARTRF0_TXC" value="USARTRF0_TXC"/>
        <enumValue label="USARTRF0_RXDATAV" value="USARTRF0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_USART2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART2_TXC" value="USART2_TXC"/>
        <enumValue label="USART2_RXDATAV" value="USART2_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_UART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART0_TXC" value="UART0_TXC"/>
        <enumValue label="UART0_RXDATAV" value="UART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_UART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART1_TXC" value="UART1_TXC"/>
        <enumValue label="UART1_RXDATAV" value="UART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_OF" value="BURTC_OF"/>
        <enumValue label="BURTC_COMP0" value="BURTC_COMP0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_SCANRES0" value="LESENSE_SCANRES0"/>
        <enumValue label="LESENSE_SCANRES1" value="LESENSE_SCANRES1"/>
        <enumValue label="LESENSE_SCANRES2" value="LESENSE_SCANRES2"/>
        <enumValue label="LESENSE_SCANRES3" value="LESENSE_SCANRES3"/>
        <enumValue label="LESENSE_SCANRES4" value="LESENSE_SCANRES4"/>
        <enumValue label="LESENSE_SCANRES5" value="LESENSE_SCANRES5"/>
        <enumValue label="LESENSE_SCANRES6" value="LESENSE_SCANRES6"/>
        <enumValue label="LESENSE_SCANRES7" value="LESENSE_SCANRES7"/>
        <enumValue label="LESENSE_SCANRES8" value="LESENSE_SCANRES8"/>
        <enumValue label="LESENSE_SCANRES9" value="LESENSE_SCANRES9"/>
        <enumValue label="LESENSE_SCANRES10" value="LESENSE_SCANRES10"/>
        <enumValue label="LESENSE_SCANRES11" value="LESENSE_SCANRES11"/>
        <enumValue label="LESENSE_SCANRES12" value="LESENSE_SCANRES12"/>
        <enumValue label="LESENSE_SCANRES13" value="LESENSE_SCANRES13"/>
        <enumValue label="LESENSE_SCANRES14" value="LESENSE_SCANRES14"/>
        <enumValue label="LESENSE_SCANRES15" value="LESENSE_SCANRES15"/>
        <enumValue label="LESENSE_DEC0" value="LESENSE_DEC0"/>
        <enumValue label="LESENSE_DEC1" value="LESENSE_DEC1"/>
        <enumValue label="LESENSE_DEC2" value="LESENSE_DEC2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch3_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH3.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH4.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH4_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="DAC0" value="DAC0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USARTRF0" value="USARTRF0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="USART2" value="USART2"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="UART0" value="UART0"/>
        <enumValue label="UART1" value="UART1"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="LESENSE" value="LESENSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_DAC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="DAC0_CH0" value="DAC0_CH0"/>
        <enumValue label="DAC0_CH1" value="DAC0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_USARTRF0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USARTRF0_IRTX" value="USARTRF0_IRTX"/>
        <enumValue label="USARTRF0_TXC" value="USARTRF0_TXC"/>
        <enumValue label="USARTRF0_RXDATAV" value="USARTRF0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_USART2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART2_TXC" value="USART2_TXC"/>
        <enumValue label="USART2_RXDATAV" value="USART2_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_UART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART0_TXC" value="UART0_TXC"/>
        <enumValue label="UART0_RXDATAV" value="UART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_UART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART1_TXC" value="UART1_TXC"/>
        <enumValue label="UART1_RXDATAV" value="UART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_OF" value="BURTC_OF"/>
        <enumValue label="BURTC_COMP0" value="BURTC_COMP0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_SCANRES0" value="LESENSE_SCANRES0"/>
        <enumValue label="LESENSE_SCANRES1" value="LESENSE_SCANRES1"/>
        <enumValue label="LESENSE_SCANRES2" value="LESENSE_SCANRES2"/>
        <enumValue label="LESENSE_SCANRES3" value="LESENSE_SCANRES3"/>
        <enumValue label="LESENSE_SCANRES4" value="LESENSE_SCANRES4"/>
        <enumValue label="LESENSE_SCANRES5" value="LESENSE_SCANRES5"/>
        <enumValue label="LESENSE_SCANRES6" value="LESENSE_SCANRES6"/>
        <enumValue label="LESENSE_SCANRES7" value="LESENSE_SCANRES7"/>
        <enumValue label="LESENSE_SCANRES8" value="LESENSE_SCANRES8"/>
        <enumValue label="LESENSE_SCANRES9" value="LESENSE_SCANRES9"/>
        <enumValue label="LESENSE_SCANRES10" value="LESENSE_SCANRES10"/>
        <enumValue label="LESENSE_SCANRES11" value="LESENSE_SCANRES11"/>
        <enumValue label="LESENSE_SCANRES12" value="LESENSE_SCANRES12"/>
        <enumValue label="LESENSE_SCANRES13" value="LESENSE_SCANRES13"/>
        <enumValue label="LESENSE_SCANRES14" value="LESENSE_SCANRES14"/>
        <enumValue label="LESENSE_SCANRES15" value="LESENSE_SCANRES15"/>
        <enumValue label="LESENSE_DEC0" value="LESENSE_DEC0"/>
        <enumValue label="LESENSE_DEC1" value="LESENSE_DEC1"/>
        <enumValue label="LESENSE_DEC2" value="LESENSE_DEC2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch4_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <stringProperty label="Custom name" id="PRS.custom_name_CH5.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH5_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="DAC0" value="DAC0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USARTRF0" value="USARTRF0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="USART2" value="USART2"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="UART0" value="UART0"/>
        <enumValue label="UART1" value="UART1"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="LESENSE" value="LESENSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_DAC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="DAC0_CH0" value="DAC0_CH0"/>
        <enumValue label="DAC0_CH1" value="DAC0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_USARTRF0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USARTRF0_IRTX" value="USARTRF0_IRTX"/>
        <enumValue label="USARTRF0_TXC" value="USARTRF0_TXC"/>
        <enumValue label="USARTRF0_RXDATAV" value="USARTRF0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_USART2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART2_TXC" value="USART2_TXC"/>
        <enumValue label="USART2_RXDATAV" value="USART2_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_UART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART0_TXC" value="UART0_TXC"/>
        <enumValue label="UART0_RXDATAV" value="UART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_UART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART1_TXC" value="UART1_TXC"/>
        <enumValue label="UART1_RXDATAV" value="UART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_OF" value="BURTC_OF"/>
        <enumValue label="BURTC_COMP0" value="BURTC_COMP0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_SCANRES0" value="LESENSE_SCANRES0"/>
        <enumValue label="LESENSE_SCANRES1" value="LESENSE_SCANRES1"/>
        <enumValue label="LESENSE_SCANRES2" value="LESENSE_SCANRES2"/>
        <enumValue label="LESENSE_SCANRES3" value="LESENSE_SCANRES3"/>
        <enumValue label="LESENSE_SCANRES4" value="LESENSE_SCANRES4"/>
        <enumValue label="LESENSE_SCANRES5" value="LESENSE_SCANRES5"/>
        <enumValue label="LESENSE_SCANRES6" value="LESENSE_SCANRES6"/>
        <enumValue label="LESENSE_SCANRES7" value="LESENSE_SCANRES7"/>
        <enumValue label="LESENSE_SCANRES8" value="LESENSE_SCANRES8"/>
        <enumValue label="LESENSE_SCANRES9" value="LESENSE_SCANRES9"/>
        <enumValue label="LESENSE_SCANRES10" value="LESENSE_SCANRES10"/>
        <enumValue label="LESENSE_SCANRES11" value="LESENSE_SCANRES11"/>
        <enumValue label="LESENSE_SCANRES12" value="LESENSE_SCANRES12"/>
        <enumValue label="LESENSE_SCANRES13" value="LESENSE_SCANRES13"/>
        <enumValue label="LESENSE_SCANRES14" value="LESENSE_SCANRES14"/>
        <enumValue label="LESENSE_SCANRES15" value="LESENSE_SCANRES15"/>
        <enumValue label="LESENSE_DEC0" value="LESENSE_DEC0"/>
        <enumValue label="LESENSE_DEC1" value="LESENSE_DEC1"/>
        <enumValue label="LESENSE_DEC2" value="LESENSE_DEC2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch5_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <stringProperty label="Custom name" id="PRS.custom_name_CH6.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH6_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="DAC0" value="DAC0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USARTRF0" value="USARTRF0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="USART2" value="USART2"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="UART0" value="UART0"/>
        <enumValue label="UART1" value="UART1"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="LESENSE" value="LESENSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_DAC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="DAC0_CH0" value="DAC0_CH0"/>
        <enumValue label="DAC0_CH1" value="DAC0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_USARTRF0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USARTRF0_IRTX" value="USARTRF0_IRTX"/>
        <enumValue label="USARTRF0_TXC" value="USARTRF0_TXC"/>
        <enumValue label="USARTRF0_RXDATAV" value="USARTRF0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_USART2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART2_TXC" value="USART2_TXC"/>
        <enumValue label="USART2_RXDATAV" value="USART2_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_UART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART0_TXC" value="UART0_TXC"/>
        <enumValue label="UART0_RXDATAV" value="UART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_UART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART1_TXC" value="UART1_TXC"/>
        <enumValue label="UART1_RXDATAV" value="UART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_OF" value="BURTC_OF"/>
        <enumValue label="BURTC_COMP0" value="BURTC_COMP0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_SCANRES0" value="LESENSE_SCANRES0"/>
        <enumValue label="LESENSE_SCANRES1" value="LESENSE_SCANRES1"/>
        <enumValue label="LESENSE_SCANRES2" value="LESENSE_SCANRES2"/>
        <enumValue label="LESENSE_SCANRES3" value="LESENSE_SCANRES3"/>
        <enumValue label="LESENSE_SCANRES4" value="LESENSE_SCANRES4"/>
        <enumValue label="LESENSE_SCANRES5" value="LESENSE_SCANRES5"/>
        <enumValue label="LESENSE_SCANRES6" value="LESENSE_SCANRES6"/>
        <enumValue label="LESENSE_SCANRES7" value="LESENSE_SCANRES7"/>
        <enumValue label="LESENSE_SCANRES8" value="LESENSE_SCANRES8"/>
        <enumValue label="LESENSE_SCANRES9" value="LESENSE_SCANRES9"/>
        <enumValue label="LESENSE_SCANRES10" value="LESENSE_SCANRES10"/>
        <enumValue label="LESENSE_SCANRES11" value="LESENSE_SCANRES11"/>
        <enumValue label="LESENSE_SCANRES12" value="LESENSE_SCANRES12"/>
        <enumValue label="LESENSE_SCANRES13" value="LESENSE_SCANRES13"/>
        <enumValue label="LESENSE_SCANRES14" value="LESENSE_SCANRES14"/>
        <enumValue label="LESENSE_SCANRES15" value="LESENSE_SCANRES15"/>
        <enumValue label="LESENSE_DEC0" value="LESENSE_DEC0"/>
        <enumValue label="LESENSE_DEC1" value="LESENSE_DEC1"/>
        <enumValue label="LESENSE_DEC2" value="LESENSE_DEC2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch6_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <stringProperty label="Custom name" id="PRS.custom_name_CH7.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH7_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="DAC0" value="DAC0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USARTRF0" value="USARTRF0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="USART2" value="USART2"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="UART0" value="UART0"/>
        <enumValue label="UART1" value="UART1"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="LESENSE" value="LESENSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_DAC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="DAC0_CH0" value="DAC0_CH0"/>
        <enumValue label="DAC0_CH1" value="DAC0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_USARTRF0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USARTRF0_IRTX" value="USARTRF0_IRTX"/>
        <enumValue label="USARTRF0_TXC" value="USARTRF0_TXC"/>
        <enumValue label="USARTRF0_RXDATAV" value="USARTRF0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_USART2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART2_TXC" value="USART2_TXC"/>
        <enumValue label="USART2_RXDATAV" value="USART2_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_UART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART0_TXC" value="UART0_TXC"/>
        <enumValue label="UART0_RXDATAV" value="UART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_UART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART1_TXC" value="UART1_TXC"/>
        <enumValue label="UART1_RXDATAV" value="UART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_OF" value="BURTC_OF"/>
        <enumValue label="BURTC_COMP0" value="BURTC_COMP0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_SCANRES0" value="LESENSE_SCANRES0"/>
        <enumValue label="LESENSE_SCANRES1" value="LESENSE_SCANRES1"/>
        <enumValue label="LESENSE_SCANRES2" value="LESENSE_SCANRES2"/>
        <enumValue label="LESENSE_SCANRES3" value="LESENSE_SCANRES3"/>
        <enumValue label="LESENSE_SCANRES4" value="LESENSE_SCANRES4"/>
        <enumValue label="LESENSE_SCANRES5" value="LESENSE_SCANRES5"/>
        <enumValue label="LESENSE_SCANRES6" value="LESENSE_SCANRES6"/>
        <enumValue label="LESENSE_SCANRES7" value="LESENSE_SCANRES7"/>
        <enumValue label="LESENSE_SCANRES8" value="LESENSE_SCANRES8"/>
        <enumValue label="LESENSE_SCANRES9" value="LESENSE_SCANRES9"/>
        <enumValue label="LESENSE_SCANRES10" value="LESENSE_SCANRES10"/>
        <enumValue label="LESENSE_SCANRES11" value="LESENSE_SCANRES11"/>
        <enumValue label="LESENSE_SCANRES12" value="LESENSE_SCANRES12"/>
        <enumValue label="LESENSE_SCANRES13" value="LESENSE_SCANRES13"/>
        <enumValue label="LESENSE_SCANRES14" value="LESENSE_SCANRES14"/>
        <enumValue label="LESENSE_SCANRES15" value="LESENSE_SCANRES15"/>
        <enumValue label="LESENSE_DEC0" value="LESENSE_DEC0"/>
        <enumValue label="LESENSE_DEC1" value="LESENSE_DEC1"/>
        <enumValue label="LESENSE_DEC2" value="LESENSE_DEC2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch7_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <stringProperty label="Custom name" id="PRS.custom_name_CH8.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH8_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="DAC0" value="DAC0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USARTRF0" value="USARTRF0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="USART2" value="USART2"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="UART0" value="UART0"/>
        <enumValue label="UART1" value="UART1"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="LESENSE" value="LESENSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_DAC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="DAC0_CH0" value="DAC0_CH0"/>
        <enumValue label="DAC0_CH1" value="DAC0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_USARTRF0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USARTRF0_IRTX" value="USARTRF0_IRTX"/>
        <enumValue label="USARTRF0_TXC" value="USARTRF0_TXC"/>
        <enumValue label="USARTRF0_RXDATAV" value="USARTRF0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_USART2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART2_TXC" value="USART2_TXC"/>
        <enumValue label="USART2_RXDATAV" value="USART2_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_UART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART0_TXC" value="UART0_TXC"/>
        <enumValue label="UART0_RXDATAV" value="UART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_UART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART1_TXC" value="UART1_TXC"/>
        <enumValue label="UART1_RXDATAV" value="UART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_OF" value="BURTC_OF"/>
        <enumValue label="BURTC_COMP0" value="BURTC_COMP0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_SCANRES0" value="LESENSE_SCANRES0"/>
        <enumValue label="LESENSE_SCANRES1" value="LESENSE_SCANRES1"/>
        <enumValue label="LESENSE_SCANRES2" value="LESENSE_SCANRES2"/>
        <enumValue label="LESENSE_SCANRES3" value="LESENSE_SCANRES3"/>
        <enumValue label="LESENSE_SCANRES4" value="LESENSE_SCANRES4"/>
        <enumValue label="LESENSE_SCANRES5" value="LESENSE_SCANRES5"/>
        <enumValue label="LESENSE_SCANRES6" value="LESENSE_SCANRES6"/>
        <enumValue label="LESENSE_SCANRES7" value="LESENSE_SCANRES7"/>
        <enumValue label="LESENSE_SCANRES8" value="LESENSE_SCANRES8"/>
        <enumValue label="LESENSE_SCANRES9" value="LESENSE_SCANRES9"/>
        <enumValue label="LESENSE_SCANRES10" value="LESENSE_SCANRES10"/>
        <enumValue label="LESENSE_SCANRES11" value="LESENSE_SCANRES11"/>
        <enumValue label="LESENSE_SCANRES12" value="LESENSE_SCANRES12"/>
        <enumValue label="LESENSE_SCANRES13" value="LESENSE_SCANRES13"/>
        <enumValue label="LESENSE_SCANRES14" value="LESENSE_SCANRES14"/>
        <enumValue label="LESENSE_SCANRES15" value="LESENSE_SCANRES15"/>
        <enumValue label="LESENSE_DEC0" value="LESENSE_DEC0"/>
        <enumValue label="LESENSE_DEC1" value="LESENSE_DEC1"/>
        <enumValue label="LESENSE_DEC2" value="LESENSE_DEC2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch8_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <stringProperty label="Custom name" id="PRS.custom_name_CH9.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH9_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="DAC0" value="DAC0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USARTRF0" value="USARTRF0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="USART2" value="USART2"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="UART0" value="UART0"/>
        <enumValue label="UART1" value="UART1"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="LESENSE" value="LESENSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_DAC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="DAC0_CH0" value="DAC0_CH0"/>
        <enumValue label="DAC0_CH1" value="DAC0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_USARTRF0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USARTRF0_IRTX" value="USARTRF0_IRTX"/>
        <enumValue label="USARTRF0_TXC" value="USARTRF0_TXC"/>
        <enumValue label="USARTRF0_RXDATAV" value="USARTRF0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_USART2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART2_TXC" value="USART2_TXC"/>
        <enumValue label="USART2_RXDATAV" value="USART2_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_UART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART0_TXC" value="UART0_TXC"/>
        <enumValue label="UART0_RXDATAV" value="UART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_UART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART1_TXC" value="UART1_TXC"/>
        <enumValue label="UART1_RXDATAV" value="UART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_OF" value="BURTC_OF"/>
        <enumValue label="BURTC_COMP0" value="BURTC_COMP0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_SCANRES0" value="LESENSE_SCANRES0"/>
        <enumValue label="LESENSE_SCANRES1" value="LESENSE_SCANRES1"/>
        <enumValue label="LESENSE_SCANRES2" value="LESENSE_SCANRES2"/>
        <enumValue label="LESENSE_SCANRES3" value="LESENSE_SCANRES3"/>
        <enumValue label="LESENSE_SCANRES4" value="LESENSE_SCANRES4"/>
        <enumValue label="LESENSE_SCANRES5" value="LESENSE_SCANRES5"/>
        <enumValue label="LESENSE_SCANRES6" value="LESENSE_SCANRES6"/>
        <enumValue label="LESENSE_SCANRES7" value="LESENSE_SCANRES7"/>
        <enumValue label="LESENSE_SCANRES8" value="LESENSE_SCANRES8"/>
        <enumValue label="LESENSE_SCANRES9" value="LESENSE_SCANRES9"/>
        <enumValue label="LESENSE_SCANRES10" value="LESENSE_SCANRES10"/>
        <enumValue label="LESENSE_SCANRES11" value="LESENSE_SCANRES11"/>
        <enumValue label="LESENSE_SCANRES12" value="LESENSE_SCANRES12"/>
        <enumValue label="LESENSE_SCANRES13" value="LESENSE_SCANRES13"/>
        <enumValue label="LESENSE_SCANRES14" value="LESENSE_SCANRES14"/>
        <enumValue label="LESENSE_SCANRES15" value="LESENSE_SCANRES15"/>
        <enumValue label="LESENSE_DEC0" value="LESENSE_DEC0"/>
        <enumValue label="LESENSE_DEC1" value="LESENSE_DEC1"/>
        <enumValue label="LESENSE_DEC2" value="LESENSE_DEC2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch9_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <stringProperty label="Custom name" id="PRS.custom_name_CH10.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH10_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="DAC0" value="DAC0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USARTRF0" value="USARTRF0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="USART2" value="USART2"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="UART0" value="UART0"/>
        <enumValue label="UART1" value="UART1"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="LESENSE" value="LESENSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_DAC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="DAC0_CH0" value="DAC0_CH0"/>
        <enumValue label="DAC0_CH1" value="DAC0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_USARTRF0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USARTRF0_IRTX" value="USARTRF0_IRTX"/>
        <enumValue label="USARTRF0_TXC" value="USARTRF0_TXC"/>
        <enumValue label="USARTRF0_RXDATAV" value="USARTRF0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_USART2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART2_TXC" value="USART2_TXC"/>
        <enumValue label="USART2_RXDATAV" value="USART2_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_UART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART0_TXC" value="UART0_TXC"/>
        <enumValue label="UART0_RXDATAV" value="UART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_UART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART1_TXC" value="UART1_TXC"/>
        <enumValue label="UART1_RXDATAV" value="UART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_OF" value="BURTC_OF"/>
        <enumValue label="BURTC_COMP0" value="BURTC_COMP0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_SCANRES0" value="LESENSE_SCANRES0"/>
        <enumValue label="LESENSE_SCANRES1" value="LESENSE_SCANRES1"/>
        <enumValue label="LESENSE_SCANRES2" value="LESENSE_SCANRES2"/>
        <enumValue label="LESENSE_SCANRES3" value="LESENSE_SCANRES3"/>
        <enumValue label="LESENSE_SCANRES4" value="LESENSE_SCANRES4"/>
        <enumValue label="LESENSE_SCANRES5" value="LESENSE_SCANRES5"/>
        <enumValue label="LESENSE_SCANRES6" value="LESENSE_SCANRES6"/>
        <enumValue label="LESENSE_SCANRES7" value="LESENSE_SCANRES7"/>
        <enumValue label="LESENSE_SCANRES8" value="LESENSE_SCANRES8"/>
        <enumValue label="LESENSE_SCANRES9" value="LESENSE_SCANRES9"/>
        <enumValue label="LESENSE_SCANRES10" value="LESENSE_SCANRES10"/>
        <enumValue label="LESENSE_SCANRES11" value="LESENSE_SCANRES11"/>
        <enumValue label="LESENSE_SCANRES12" value="LESENSE_SCANRES12"/>
        <enumValue label="LESENSE_SCANRES13" value="LESENSE_SCANRES13"/>
        <enumValue label="LESENSE_SCANRES14" value="LESENSE_SCANRES14"/>
        <enumValue label="LESENSE_SCANRES15" value="LESENSE_SCANRES15"/>
        <enumValue label="LESENSE_DEC0" value="LESENSE_DEC0"/>
        <enumValue label="LESENSE_DEC1" value="LESENSE_DEC1"/>
        <enumValue label="LESENSE_DEC2" value="LESENSE_DEC2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch10_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <stringProperty label="Custom name" id="PRS.custom_name_CH11.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH11_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="VCMP" value="VCMP"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="DAC0" value="DAC0"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USARTRF0" value="USARTRF0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="USART2" value="USART2"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="TIMER2" value="TIMER2"/>
        <enumValue label="TIMER3" value="TIMER3"/>
        <enumValue label="USB" value="USB"/>
        <enumValue label="RTC" value="RTC"/>
        <enumValue label="UART0" value="UART0"/>
        <enumValue label="UART1" value="UART1"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="BURTC" value="BURTC"/>
        <enumValue label="LESENSE" value="LESENSE"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_VCMP.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="VCMP_OUT" value="VCMP_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_DAC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="DAC0_CH0" value="DAC0_CH0"/>
        <enumValue label="DAC0_CH1" value="DAC0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_USARTRF0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USARTRF0_IRTX" value="USARTRF0_IRTX"/>
        <enumValue label="USARTRF0_TXC" value="USARTRF0_TXC"/>
        <enumValue label="USARTRF0_RXDATAV" value="USARTRF0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_USART2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART2_TXC" value="USART2_TXC"/>
        <enumValue label="USART2_RXDATAV" value="USART2_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER2.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER2_UF" value="TIMER2_UF"/>
        <enumValue label="TIMER2_OF" value="TIMER2_OF"/>
        <enumValue label="TIMER2_CC0" value="TIMER2_CC0"/>
        <enumValue label="TIMER2_CC1" value="TIMER2_CC1"/>
        <enumValue label="TIMER2_CC2" value="TIMER2_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER3.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER3_UF" value="TIMER3_UF"/>
        <enumValue label="TIMER3_OF" value="TIMER3_OF"/>
        <enumValue label="TIMER3_CC0" value="TIMER3_CC0"/>
        <enumValue label="TIMER3_CC1" value="TIMER3_CC1"/>
        <enumValue label="TIMER3_CC2" value="TIMER3_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_USB.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USB_SOF" value="USB_SOF"/>
        <enumValue label="USB_SOFSR" value="USB_SOFSR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_RTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTC_OF" value="RTC_OF"/>
        <enumValue label="RTC_COMP0" value="RTC_COMP0"/>
        <enumValue label="RTC_COMP1" value="RTC_COMP1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_UART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART0_TXC" value="UART0_TXC"/>
        <enumValue label="UART0_RXDATAV" value="UART0_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_UART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="UART1_TXC" value="UART1_TXC"/>
        <enumValue label="UART1_RXDATAV" value="UART1_RXDATAV"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_BURTC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="BURTC_OF" value="BURTC_OF"/>
        <enumValue label="BURTC_COMP0" value="BURTC_COMP0"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_LESENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LESENSE_SCANRES0" value="LESENSE_SCANRES0"/>
        <enumValue label="LESENSE_SCANRES1" value="LESENSE_SCANRES1"/>
        <enumValue label="LESENSE_SCANRES2" value="LESENSE_SCANRES2"/>
        <enumValue label="LESENSE_SCANRES3" value="LESENSE_SCANRES3"/>
        <enumValue label="LESENSE_SCANRES4" value="LESENSE_SCANRES4"/>
        <enumValue label="LESENSE_SCANRES5" value="LESENSE_SCANRES5"/>
        <enumValue label="LESENSE_SCANRES6" value="LESENSE_SCANRES6"/>
        <enumValue label="LESENSE_SCANRES7" value="LESENSE_SCANRES7"/>
        <enumValue label="LESENSE_SCANRES8" value="LESENSE_SCANRES8"/>
        <enumValue label="LESENSE_SCANRES9" value="LESENSE_SCANRES9"/>
        <enumValue label="LESENSE_SCANRES10" value="LESENSE_SCANRES10"/>
        <enumValue label="LESENSE_SCANRES11" value="LESENSE_SCANRES11"/>
        <enumValue label="LESENSE_SCANRES12" value="LESENSE_SCANRES12"/>
        <enumValue label="LESENSE_SCANRES13" value="LESENSE_SCANRES13"/>
        <enumValue label="LESENSE_SCANRES14" value="LESENSE_SCANRES14"/>
        <enumValue label="LESENSE_SCANRES15" value="LESENSE_SCANRES15"/>
        <enumValue label="LESENSE_DEC0" value="LESENSE_DEC0"/>
        <enumValue label="LESENSE_DEC1" value="LESENSE_DEC1"/>
        <enumValue label="LESENSE_DEC2" value="LESENSE_DEC2"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch11_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
    </properties>
    <propertyCategories>
      <category label="PRS">
        <subCategory label="">
          <propertyRef refId="PRS.usedbysdk.BOOL"/>
          <propertyRef refId="PRS.hiddenbysdk.BOOL"/>
          <propertyRef refId="PRS.showadvanced.BOOL"/>
          <propertyRef refId="PRS.forceenable.BOOL"/>
          <propertyRef refId="PRS.owner.STRING"/>
        </subCategory>
        <subCategory label="CH0 properties">
          <propertyRef refId="PRS.custom_name_CH0.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_DAC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_USARTRF0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_USART2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_UART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_UART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch0_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH0.PIN"/>
        </subCategory>
        <subCategory label="CH1 properties">
          <propertyRef refId="PRS.custom_name_CH1.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_DAC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_USARTRF0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_USART2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_UART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_UART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch1_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH1.PIN"/>
        </subCategory>
        <subCategory label="CH2 properties">
          <propertyRef refId="PRS.custom_name_CH2.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_DAC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_USARTRF0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_USART2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_UART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_UART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch2_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH2.PIN"/>
        </subCategory>
        <subCategory label="CH3 properties">
          <propertyRef refId="PRS.custom_name_CH3.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_DAC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_USARTRF0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_USART2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_UART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_UART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch3_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH3.PIN"/>
        </subCategory>
        <subCategory label="CH4 properties">
          <propertyRef refId="PRS.custom_name_CH4.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_DAC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_USARTRF0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_USART2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_UART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_UART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch4_signal_disabled.STRING"/>
        </subCategory>
        <subCategory label="CH5 properties">
          <propertyRef refId="PRS.custom_name_CH5.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_DAC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_USARTRF0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_USART2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_UART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_UART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch5_signal_disabled.STRING"/>
        </subCategory>
        <subCategory label="CH6 properties">
          <propertyRef refId="PRS.custom_name_CH6.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_DAC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_USARTRF0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_USART2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_UART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_UART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch6_signal_disabled.STRING"/>
        </subCategory>
        <subCategory label="CH7 properties">
          <propertyRef refId="PRS.custom_name_CH7.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_DAC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_USARTRF0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_USART2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_UART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_UART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch7_signal_disabled.STRING"/>
        </subCategory>
        <subCategory label="CH8 properties">
          <propertyRef refId="PRS.custom_name_CH8.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_DAC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_USARTRF0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_USART2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_UART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_UART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch8_signal_disabled.STRING"/>
        </subCategory>
        <subCategory label="CH9 properties">
          <propertyRef refId="PRS.custom_name_CH9.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_DAC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_USARTRF0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_USART2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_UART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_UART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch9_signal_disabled.STRING"/>
        </subCategory>
        <subCategory label="CH10 properties">
          <propertyRef refId="PRS.custom_name_CH10.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_DAC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_USARTRF0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_USART2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_UART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_UART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch10_signal_disabled.STRING"/>
        </subCategory>
        <subCategory label="CH11 properties">
          <propertyRef refId="PRS.custom_name_CH11.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_VCMP.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_DAC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_USARTRF0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_USART2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER2.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER3.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_USB.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_RTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_UART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_UART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_BURTC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_LESENSE.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch11_signal_disabled.STRING"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
