<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efm32.efm32zg.emu" label="EMU" name="EMU" description="Energy Management Unit" version="efm">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="EMU.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="EMU.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="EMU.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="EMU.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="EMU.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <enumProperty label="Enable full VREG drive strength in EM2/3" description="Enable full drive strength for the voltage regulator in EM2 and EM3" id="EMU.HAL_EMU_EM23_VREG.BOOL" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
    </properties>
    <propertyCategories>
      <category label="EMU">
        <subCategory label="">
          <propertyRef refId="EMU.usedbysdk.BOOL"/>
          <propertyRef refId="EMU.hiddenbysdk.BOOL"/>
          <propertyRef refId="EMU.showadvanced.BOOL"/>
          <propertyRef refId="EMU.forceenable.BOOL"/>
          <propertyRef refId="EMU.owner.STRING"/>
          <propertyRef refId="EMU.HAL_EMU_EM23_VREG.BOOL"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
