<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efr32.efr32fg13p.idac0" label="IDAC0" name="IDAC0" description="" version="efr">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="IDAC.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="IDAC.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="IDAC.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="IDAC.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="IDAC.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <stringProperty label="Custom name" id="IDAC.customname.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Output selection" id="IDAC.BSP_IDAC_OUTPUT.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="APORT bus CX" value="APORT1X"/>
        <enumValue label="APORT bus CY" value="APORT1Y"/>
      </enumProperty>
      <enumProperty label="Channel on APORT bus CX (OUT)" id="IDAC.bsp_idac_out_CX.PIN" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Channel on APORT bus CY (OUT)" id="IDAC.bsp_idac_out_CY.PIN" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
    </properties>
    <propertyCategories>
      <category label="IDAC0">
        <subCategory label="">
          <propertyRef refId="IDAC.usedbysdk.BOOL"/>
          <propertyRef refId="IDAC.hiddenbysdk.BOOL"/>
          <propertyRef refId="IDAC.showadvanced.BOOL"/>
          <propertyRef refId="IDAC.forceenable.BOOL"/>
          <propertyRef refId="IDAC.owner.STRING"/>
          <propertyRef refId="IDAC.customname.STRING"/>
        </subCategory>
        <subCategory label="Output">
          <propertyRef refId="IDAC.BSP_IDAC_OUTPUT.ENUM"/>
          <propertyRef refId="IDAC.bsp_idac_out_CX.PIN"/>
          <propertyRef refId="IDAC.bsp_idac_out_CY.PIN"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
