// This is an autogenerated config file, any changes to this file will be overwritten

#ifndef SLI_PSA_BUILTIN_CONFIG_AUTOGEN_H
#define SLI_PSA_BUILTIN_CONFIG_AUTOGEN_H

// Don't need these features
// #define MBEDTLS_PSA_BUILTIN_ALG_ECB_NO_PADDING 1
// #define MBEDTLS_PSA_BUILTIN_ALG_CMAC 1

#endif // SLI_PSA_BUILTIN_CONFIG_AUTOGEN_H
