<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efr32.efr32bg13p.emu" label="EMU" name="EMU" description="Energy Management Unit" version="efr">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="EMU.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="EMU.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="EMU.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="EMU.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="EMU.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <enumProperty label="Enable voltage scaling in EM0/1" description="Enable automatic voltage scaling in EM0 and EM1. The voltage scale level will depend on the HF clock frequency at any given time. Should not be used in combination with radio." id="EMU.HAL_EMU_EM01_VSCALE.BOOL" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="EM2/3 voltage scaling level " description="Set voltage scaling level in EM2 and EM3." id="EMU.HAL_EMU_EM23_VSCALE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Fast wakeup" value="HAL_EMU_EM23_VSCALE_FASTWAKEUP"/>
        <enumValue label="Low power" value="HAL_EMU_EM23_VSCALE_LOWPOWER"/>
      </enumProperty>
    </properties>
    <propertyCategories>
      <category label="EMU">
        <subCategory label="">
          <propertyRef refId="EMU.usedbysdk.BOOL"/>
          <propertyRef refId="EMU.hiddenbysdk.BOOL"/>
          <propertyRef refId="EMU.showadvanced.BOOL"/>
          <propertyRef refId="EMU.forceenable.BOOL"/>
          <propertyRef refId="EMU.owner.STRING"/>
          <propertyRef refId="EMU.HAL_EMU_EM01_VSCALE.BOOL"/>
          <propertyRef refId="EMU.HAL_EMU_EM23_VSCALE.ENUM"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
