<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efr32.efr32mg1b.prs" label="PRS" name="PRS" description="" version="efr">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="PRS.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="PRS.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="PRS.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="PRS.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="PRS.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <stringProperty label="Custom name" id="PRS.custom_name_CH0.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH0_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="RAC" value="RAC"/>
        <enumValue label="PROTIMER" value="PROTIMER"/>
        <enumValue label="MODEM" value="MODEM"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="RFSENSE" value="RFSENSE"/>
        <enumValue label="CRYOTIMER" value="CRYOTIMER"/>
        <enumValue label="CMU" value="CMU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_CH0" value="PRS_CH0"/>
        <enumValue label="PRS_CH1" value="PRS_CH1"/>
        <enumValue label="PRS_CH2" value="PRS_CH2"/>
        <enumValue label="PRS_CH3" value="PRS_CH3"/>
        <enumValue label="PRS_CH4" value="PRS_CH4"/>
        <enumValue label="PRS_CH5" value="PRS_CH5"/>
        <enumValue label="PRS_CH6" value="PRS_CH6"/>
        <enumValue label="PRS_CH7" value="PRS_CH7"/>
        <enumValue label="PRS_CH8" value="PRS_CH8"/>
        <enumValue label="PRS_CH9" value="PRS_CH9"/>
        <enumValue label="PRS_CH10" value="PRS_CH10"/>
        <enumValue label="PRS_CH11" value="PRS_CH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_CS" value="USART0_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_CS" value="USART1_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
        <enumValue label="TIMER1_CC3" value="TIMER1_CC3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_RAC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RAC_ACTIVE" value="RAC_ACTIVE"/>
        <enumValue label="RAC_TX" value="RAC_TX"/>
        <enumValue label="RAC_RX" value="RAC_RX"/>
        <enumValue label="RAC_LNAEN" value="RAC_LNAEN"/>
        <enumValue label="RAC_PAEN" value="RAC_PAEN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_PROTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PROTIMER_LBTS" value="PROTIMER_LBTS"/>
        <enumValue label="PROTIMER_LBTR" value="PROTIMER_LBTR"/>
        <enumValue label="PROTIMER_LBTF" value="PROTIMER_LBTF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_MODEM.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="MODEM_FRAMEDET" value="MODEM_FRAMEDET"/>
        <enumValue label="MODEM_PREDET" value="MODEM_PREDET"/>
        <enumValue label="MODEM_TIMDET" value="MODEM_TIMDET"/>
        <enumValue label="MODEM_FRAMESENT" value="MODEM_FRAMESENT"/>
        <enumValue label="MODEM_SYNCSENT" value="MODEM_SYNCSENT"/>
        <enumValue label="MODEM_PRESENT" value="MODEM_PRESENT"/>
        <enumValue label="MODEM_ANT0" value="MODEM_ANT0"/>
        <enumValue label="MODEM_ANT1" value="MODEM_ANT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_RFSENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RFSENSE_WU" value="RFSENSE_WU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_CRYOTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CRYOTIMER_PERIOD" value="CRYOTIMER_PERIOD"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH0_SIGNAL_CMU.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMU_CLKOUT0" value="CMU_CLKOUT0"/>
        <enumValue label="CMU_CLKOUT1" value="CMU_CLKOUT1"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch0_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH0.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH1.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH1_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="RAC" value="RAC"/>
        <enumValue label="PROTIMER" value="PROTIMER"/>
        <enumValue label="MODEM" value="MODEM"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="RFSENSE" value="RFSENSE"/>
        <enumValue label="CRYOTIMER" value="CRYOTIMER"/>
        <enumValue label="CMU" value="CMU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_CH0" value="PRS_CH0"/>
        <enumValue label="PRS_CH1" value="PRS_CH1"/>
        <enumValue label="PRS_CH2" value="PRS_CH2"/>
        <enumValue label="PRS_CH3" value="PRS_CH3"/>
        <enumValue label="PRS_CH4" value="PRS_CH4"/>
        <enumValue label="PRS_CH5" value="PRS_CH5"/>
        <enumValue label="PRS_CH6" value="PRS_CH6"/>
        <enumValue label="PRS_CH7" value="PRS_CH7"/>
        <enumValue label="PRS_CH8" value="PRS_CH8"/>
        <enumValue label="PRS_CH9" value="PRS_CH9"/>
        <enumValue label="PRS_CH10" value="PRS_CH10"/>
        <enumValue label="PRS_CH11" value="PRS_CH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_CS" value="USART0_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_CS" value="USART1_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
        <enumValue label="TIMER1_CC3" value="TIMER1_CC3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_RAC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RAC_ACTIVE" value="RAC_ACTIVE"/>
        <enumValue label="RAC_TX" value="RAC_TX"/>
        <enumValue label="RAC_RX" value="RAC_RX"/>
        <enumValue label="RAC_LNAEN" value="RAC_LNAEN"/>
        <enumValue label="RAC_PAEN" value="RAC_PAEN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_PROTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PROTIMER_LBTS" value="PROTIMER_LBTS"/>
        <enumValue label="PROTIMER_LBTR" value="PROTIMER_LBTR"/>
        <enumValue label="PROTIMER_LBTF" value="PROTIMER_LBTF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_MODEM.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="MODEM_FRAMEDET" value="MODEM_FRAMEDET"/>
        <enumValue label="MODEM_PREDET" value="MODEM_PREDET"/>
        <enumValue label="MODEM_TIMDET" value="MODEM_TIMDET"/>
        <enumValue label="MODEM_FRAMESENT" value="MODEM_FRAMESENT"/>
        <enumValue label="MODEM_SYNCSENT" value="MODEM_SYNCSENT"/>
        <enumValue label="MODEM_PRESENT" value="MODEM_PRESENT"/>
        <enumValue label="MODEM_ANT0" value="MODEM_ANT0"/>
        <enumValue label="MODEM_ANT1" value="MODEM_ANT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_RFSENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RFSENSE_WU" value="RFSENSE_WU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_CRYOTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CRYOTIMER_PERIOD" value="CRYOTIMER_PERIOD"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH1_SIGNAL_CMU.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMU_CLKOUT0" value="CMU_CLKOUT0"/>
        <enumValue label="CMU_CLKOUT1" value="CMU_CLKOUT1"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch1_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH1.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH2.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH2_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="RAC" value="RAC"/>
        <enumValue label="PROTIMER" value="PROTIMER"/>
        <enumValue label="MODEM" value="MODEM"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="RFSENSE" value="RFSENSE"/>
        <enumValue label="CRYOTIMER" value="CRYOTIMER"/>
        <enumValue label="CMU" value="CMU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_CH0" value="PRS_CH0"/>
        <enumValue label="PRS_CH1" value="PRS_CH1"/>
        <enumValue label="PRS_CH2" value="PRS_CH2"/>
        <enumValue label="PRS_CH3" value="PRS_CH3"/>
        <enumValue label="PRS_CH4" value="PRS_CH4"/>
        <enumValue label="PRS_CH5" value="PRS_CH5"/>
        <enumValue label="PRS_CH6" value="PRS_CH6"/>
        <enumValue label="PRS_CH7" value="PRS_CH7"/>
        <enumValue label="PRS_CH8" value="PRS_CH8"/>
        <enumValue label="PRS_CH9" value="PRS_CH9"/>
        <enumValue label="PRS_CH10" value="PRS_CH10"/>
        <enumValue label="PRS_CH11" value="PRS_CH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_CS" value="USART0_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_CS" value="USART1_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
        <enumValue label="TIMER1_CC3" value="TIMER1_CC3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_RAC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RAC_ACTIVE" value="RAC_ACTIVE"/>
        <enumValue label="RAC_TX" value="RAC_TX"/>
        <enumValue label="RAC_RX" value="RAC_RX"/>
        <enumValue label="RAC_LNAEN" value="RAC_LNAEN"/>
        <enumValue label="RAC_PAEN" value="RAC_PAEN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_PROTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PROTIMER_LBTS" value="PROTIMER_LBTS"/>
        <enumValue label="PROTIMER_LBTR" value="PROTIMER_LBTR"/>
        <enumValue label="PROTIMER_LBTF" value="PROTIMER_LBTF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_MODEM.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="MODEM_FRAMEDET" value="MODEM_FRAMEDET"/>
        <enumValue label="MODEM_PREDET" value="MODEM_PREDET"/>
        <enumValue label="MODEM_TIMDET" value="MODEM_TIMDET"/>
        <enumValue label="MODEM_FRAMESENT" value="MODEM_FRAMESENT"/>
        <enumValue label="MODEM_SYNCSENT" value="MODEM_SYNCSENT"/>
        <enumValue label="MODEM_PRESENT" value="MODEM_PRESENT"/>
        <enumValue label="MODEM_ANT0" value="MODEM_ANT0"/>
        <enumValue label="MODEM_ANT1" value="MODEM_ANT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_RFSENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RFSENSE_WU" value="RFSENSE_WU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_CRYOTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CRYOTIMER_PERIOD" value="CRYOTIMER_PERIOD"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH2_SIGNAL_CMU.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMU_CLKOUT0" value="CMU_CLKOUT0"/>
        <enumValue label="CMU_CLKOUT1" value="CMU_CLKOUT1"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch2_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH2.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH3.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH3_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="RAC" value="RAC"/>
        <enumValue label="PROTIMER" value="PROTIMER"/>
        <enumValue label="MODEM" value="MODEM"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="RFSENSE" value="RFSENSE"/>
        <enumValue label="CRYOTIMER" value="CRYOTIMER"/>
        <enumValue label="CMU" value="CMU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_CH0" value="PRS_CH0"/>
        <enumValue label="PRS_CH1" value="PRS_CH1"/>
        <enumValue label="PRS_CH2" value="PRS_CH2"/>
        <enumValue label="PRS_CH3" value="PRS_CH3"/>
        <enumValue label="PRS_CH4" value="PRS_CH4"/>
        <enumValue label="PRS_CH5" value="PRS_CH5"/>
        <enumValue label="PRS_CH6" value="PRS_CH6"/>
        <enumValue label="PRS_CH7" value="PRS_CH7"/>
        <enumValue label="PRS_CH8" value="PRS_CH8"/>
        <enumValue label="PRS_CH9" value="PRS_CH9"/>
        <enumValue label="PRS_CH10" value="PRS_CH10"/>
        <enumValue label="PRS_CH11" value="PRS_CH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_CS" value="USART0_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_CS" value="USART1_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
        <enumValue label="TIMER1_CC3" value="TIMER1_CC3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_RAC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RAC_ACTIVE" value="RAC_ACTIVE"/>
        <enumValue label="RAC_TX" value="RAC_TX"/>
        <enumValue label="RAC_RX" value="RAC_RX"/>
        <enumValue label="RAC_LNAEN" value="RAC_LNAEN"/>
        <enumValue label="RAC_PAEN" value="RAC_PAEN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_PROTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PROTIMER_LBTS" value="PROTIMER_LBTS"/>
        <enumValue label="PROTIMER_LBTR" value="PROTIMER_LBTR"/>
        <enumValue label="PROTIMER_LBTF" value="PROTIMER_LBTF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_MODEM.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="MODEM_FRAMEDET" value="MODEM_FRAMEDET"/>
        <enumValue label="MODEM_PREDET" value="MODEM_PREDET"/>
        <enumValue label="MODEM_TIMDET" value="MODEM_TIMDET"/>
        <enumValue label="MODEM_FRAMESENT" value="MODEM_FRAMESENT"/>
        <enumValue label="MODEM_SYNCSENT" value="MODEM_SYNCSENT"/>
        <enumValue label="MODEM_PRESENT" value="MODEM_PRESENT"/>
        <enumValue label="MODEM_ANT0" value="MODEM_ANT0"/>
        <enumValue label="MODEM_ANT1" value="MODEM_ANT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_RFSENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RFSENSE_WU" value="RFSENSE_WU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_CRYOTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CRYOTIMER_PERIOD" value="CRYOTIMER_PERIOD"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH3_SIGNAL_CMU.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMU_CLKOUT0" value="CMU_CLKOUT0"/>
        <enumValue label="CMU_CLKOUT1" value="CMU_CLKOUT1"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch3_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH3.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH4.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH4_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="RAC" value="RAC"/>
        <enumValue label="PROTIMER" value="PROTIMER"/>
        <enumValue label="MODEM" value="MODEM"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="RFSENSE" value="RFSENSE"/>
        <enumValue label="CRYOTIMER" value="CRYOTIMER"/>
        <enumValue label="CMU" value="CMU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_CH0" value="PRS_CH0"/>
        <enumValue label="PRS_CH1" value="PRS_CH1"/>
        <enumValue label="PRS_CH2" value="PRS_CH2"/>
        <enumValue label="PRS_CH3" value="PRS_CH3"/>
        <enumValue label="PRS_CH4" value="PRS_CH4"/>
        <enumValue label="PRS_CH5" value="PRS_CH5"/>
        <enumValue label="PRS_CH6" value="PRS_CH6"/>
        <enumValue label="PRS_CH7" value="PRS_CH7"/>
        <enumValue label="PRS_CH8" value="PRS_CH8"/>
        <enumValue label="PRS_CH9" value="PRS_CH9"/>
        <enumValue label="PRS_CH10" value="PRS_CH10"/>
        <enumValue label="PRS_CH11" value="PRS_CH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_CS" value="USART0_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_CS" value="USART1_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
        <enumValue label="TIMER1_CC3" value="TIMER1_CC3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_RAC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RAC_ACTIVE" value="RAC_ACTIVE"/>
        <enumValue label="RAC_TX" value="RAC_TX"/>
        <enumValue label="RAC_RX" value="RAC_RX"/>
        <enumValue label="RAC_LNAEN" value="RAC_LNAEN"/>
        <enumValue label="RAC_PAEN" value="RAC_PAEN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_PROTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PROTIMER_LBTS" value="PROTIMER_LBTS"/>
        <enumValue label="PROTIMER_LBTR" value="PROTIMER_LBTR"/>
        <enumValue label="PROTIMER_LBTF" value="PROTIMER_LBTF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_MODEM.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="MODEM_FRAMEDET" value="MODEM_FRAMEDET"/>
        <enumValue label="MODEM_PREDET" value="MODEM_PREDET"/>
        <enumValue label="MODEM_TIMDET" value="MODEM_TIMDET"/>
        <enumValue label="MODEM_FRAMESENT" value="MODEM_FRAMESENT"/>
        <enumValue label="MODEM_SYNCSENT" value="MODEM_SYNCSENT"/>
        <enumValue label="MODEM_PRESENT" value="MODEM_PRESENT"/>
        <enumValue label="MODEM_ANT0" value="MODEM_ANT0"/>
        <enumValue label="MODEM_ANT1" value="MODEM_ANT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_RFSENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RFSENSE_WU" value="RFSENSE_WU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_CRYOTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CRYOTIMER_PERIOD" value="CRYOTIMER_PERIOD"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH4_SIGNAL_CMU.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMU_CLKOUT0" value="CMU_CLKOUT0"/>
        <enumValue label="CMU_CLKOUT1" value="CMU_CLKOUT1"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch4_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH4.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH5.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH5_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="RAC" value="RAC"/>
        <enumValue label="PROTIMER" value="PROTIMER"/>
        <enumValue label="MODEM" value="MODEM"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="RFSENSE" value="RFSENSE"/>
        <enumValue label="CRYOTIMER" value="CRYOTIMER"/>
        <enumValue label="CMU" value="CMU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_CH0" value="PRS_CH0"/>
        <enumValue label="PRS_CH1" value="PRS_CH1"/>
        <enumValue label="PRS_CH2" value="PRS_CH2"/>
        <enumValue label="PRS_CH3" value="PRS_CH3"/>
        <enumValue label="PRS_CH4" value="PRS_CH4"/>
        <enumValue label="PRS_CH5" value="PRS_CH5"/>
        <enumValue label="PRS_CH6" value="PRS_CH6"/>
        <enumValue label="PRS_CH7" value="PRS_CH7"/>
        <enumValue label="PRS_CH8" value="PRS_CH8"/>
        <enumValue label="PRS_CH9" value="PRS_CH9"/>
        <enumValue label="PRS_CH10" value="PRS_CH10"/>
        <enumValue label="PRS_CH11" value="PRS_CH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_CS" value="USART0_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_CS" value="USART1_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
        <enumValue label="TIMER1_CC3" value="TIMER1_CC3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_RAC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RAC_ACTIVE" value="RAC_ACTIVE"/>
        <enumValue label="RAC_TX" value="RAC_TX"/>
        <enumValue label="RAC_RX" value="RAC_RX"/>
        <enumValue label="RAC_LNAEN" value="RAC_LNAEN"/>
        <enumValue label="RAC_PAEN" value="RAC_PAEN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_PROTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PROTIMER_LBTS" value="PROTIMER_LBTS"/>
        <enumValue label="PROTIMER_LBTR" value="PROTIMER_LBTR"/>
        <enumValue label="PROTIMER_LBTF" value="PROTIMER_LBTF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_MODEM.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="MODEM_FRAMEDET" value="MODEM_FRAMEDET"/>
        <enumValue label="MODEM_PREDET" value="MODEM_PREDET"/>
        <enumValue label="MODEM_TIMDET" value="MODEM_TIMDET"/>
        <enumValue label="MODEM_FRAMESENT" value="MODEM_FRAMESENT"/>
        <enumValue label="MODEM_SYNCSENT" value="MODEM_SYNCSENT"/>
        <enumValue label="MODEM_PRESENT" value="MODEM_PRESENT"/>
        <enumValue label="MODEM_ANT0" value="MODEM_ANT0"/>
        <enumValue label="MODEM_ANT1" value="MODEM_ANT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_RFSENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RFSENSE_WU" value="RFSENSE_WU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_CRYOTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CRYOTIMER_PERIOD" value="CRYOTIMER_PERIOD"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH5_SIGNAL_CMU.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMU_CLKOUT0" value="CMU_CLKOUT0"/>
        <enumValue label="CMU_CLKOUT1" value="CMU_CLKOUT1"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch5_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH5.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH6.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH6_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="RAC" value="RAC"/>
        <enumValue label="PROTIMER" value="PROTIMER"/>
        <enumValue label="MODEM" value="MODEM"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="RFSENSE" value="RFSENSE"/>
        <enumValue label="CRYOTIMER" value="CRYOTIMER"/>
        <enumValue label="CMU" value="CMU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_CH0" value="PRS_CH0"/>
        <enumValue label="PRS_CH1" value="PRS_CH1"/>
        <enumValue label="PRS_CH2" value="PRS_CH2"/>
        <enumValue label="PRS_CH3" value="PRS_CH3"/>
        <enumValue label="PRS_CH4" value="PRS_CH4"/>
        <enumValue label="PRS_CH5" value="PRS_CH5"/>
        <enumValue label="PRS_CH6" value="PRS_CH6"/>
        <enumValue label="PRS_CH7" value="PRS_CH7"/>
        <enumValue label="PRS_CH8" value="PRS_CH8"/>
        <enumValue label="PRS_CH9" value="PRS_CH9"/>
        <enumValue label="PRS_CH10" value="PRS_CH10"/>
        <enumValue label="PRS_CH11" value="PRS_CH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_CS" value="USART0_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_CS" value="USART1_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
        <enumValue label="TIMER1_CC3" value="TIMER1_CC3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_RAC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RAC_ACTIVE" value="RAC_ACTIVE"/>
        <enumValue label="RAC_TX" value="RAC_TX"/>
        <enumValue label="RAC_RX" value="RAC_RX"/>
        <enumValue label="RAC_LNAEN" value="RAC_LNAEN"/>
        <enumValue label="RAC_PAEN" value="RAC_PAEN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_PROTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PROTIMER_LBTS" value="PROTIMER_LBTS"/>
        <enumValue label="PROTIMER_LBTR" value="PROTIMER_LBTR"/>
        <enumValue label="PROTIMER_LBTF" value="PROTIMER_LBTF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_MODEM.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="MODEM_FRAMEDET" value="MODEM_FRAMEDET"/>
        <enumValue label="MODEM_PREDET" value="MODEM_PREDET"/>
        <enumValue label="MODEM_TIMDET" value="MODEM_TIMDET"/>
        <enumValue label="MODEM_FRAMESENT" value="MODEM_FRAMESENT"/>
        <enumValue label="MODEM_SYNCSENT" value="MODEM_SYNCSENT"/>
        <enumValue label="MODEM_PRESENT" value="MODEM_PRESENT"/>
        <enumValue label="MODEM_ANT0" value="MODEM_ANT0"/>
        <enumValue label="MODEM_ANT1" value="MODEM_ANT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_RFSENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RFSENSE_WU" value="RFSENSE_WU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_CRYOTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CRYOTIMER_PERIOD" value="CRYOTIMER_PERIOD"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH6_SIGNAL_CMU.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMU_CLKOUT0" value="CMU_CLKOUT0"/>
        <enumValue label="CMU_CLKOUT1" value="CMU_CLKOUT1"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch6_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH6.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH7.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH7_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="RAC" value="RAC"/>
        <enumValue label="PROTIMER" value="PROTIMER"/>
        <enumValue label="MODEM" value="MODEM"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="RFSENSE" value="RFSENSE"/>
        <enumValue label="CRYOTIMER" value="CRYOTIMER"/>
        <enumValue label="CMU" value="CMU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_CH0" value="PRS_CH0"/>
        <enumValue label="PRS_CH1" value="PRS_CH1"/>
        <enumValue label="PRS_CH2" value="PRS_CH2"/>
        <enumValue label="PRS_CH3" value="PRS_CH3"/>
        <enumValue label="PRS_CH4" value="PRS_CH4"/>
        <enumValue label="PRS_CH5" value="PRS_CH5"/>
        <enumValue label="PRS_CH6" value="PRS_CH6"/>
        <enumValue label="PRS_CH7" value="PRS_CH7"/>
        <enumValue label="PRS_CH8" value="PRS_CH8"/>
        <enumValue label="PRS_CH9" value="PRS_CH9"/>
        <enumValue label="PRS_CH10" value="PRS_CH10"/>
        <enumValue label="PRS_CH11" value="PRS_CH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_CS" value="USART0_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_CS" value="USART1_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
        <enumValue label="TIMER1_CC3" value="TIMER1_CC3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_RAC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RAC_ACTIVE" value="RAC_ACTIVE"/>
        <enumValue label="RAC_TX" value="RAC_TX"/>
        <enumValue label="RAC_RX" value="RAC_RX"/>
        <enumValue label="RAC_LNAEN" value="RAC_LNAEN"/>
        <enumValue label="RAC_PAEN" value="RAC_PAEN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_PROTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PROTIMER_LBTS" value="PROTIMER_LBTS"/>
        <enumValue label="PROTIMER_LBTR" value="PROTIMER_LBTR"/>
        <enumValue label="PROTIMER_LBTF" value="PROTIMER_LBTF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_MODEM.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="MODEM_FRAMEDET" value="MODEM_FRAMEDET"/>
        <enumValue label="MODEM_PREDET" value="MODEM_PREDET"/>
        <enumValue label="MODEM_TIMDET" value="MODEM_TIMDET"/>
        <enumValue label="MODEM_FRAMESENT" value="MODEM_FRAMESENT"/>
        <enumValue label="MODEM_SYNCSENT" value="MODEM_SYNCSENT"/>
        <enumValue label="MODEM_PRESENT" value="MODEM_PRESENT"/>
        <enumValue label="MODEM_ANT0" value="MODEM_ANT0"/>
        <enumValue label="MODEM_ANT1" value="MODEM_ANT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_RFSENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RFSENSE_WU" value="RFSENSE_WU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_CRYOTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CRYOTIMER_PERIOD" value="CRYOTIMER_PERIOD"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH7_SIGNAL_CMU.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMU_CLKOUT0" value="CMU_CLKOUT0"/>
        <enumValue label="CMU_CLKOUT1" value="CMU_CLKOUT1"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch7_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH7.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH8.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH8_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="RAC" value="RAC"/>
        <enumValue label="PROTIMER" value="PROTIMER"/>
        <enumValue label="MODEM" value="MODEM"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="RFSENSE" value="RFSENSE"/>
        <enumValue label="CRYOTIMER" value="CRYOTIMER"/>
        <enumValue label="CMU" value="CMU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_CH0" value="PRS_CH0"/>
        <enumValue label="PRS_CH1" value="PRS_CH1"/>
        <enumValue label="PRS_CH2" value="PRS_CH2"/>
        <enumValue label="PRS_CH3" value="PRS_CH3"/>
        <enumValue label="PRS_CH4" value="PRS_CH4"/>
        <enumValue label="PRS_CH5" value="PRS_CH5"/>
        <enumValue label="PRS_CH6" value="PRS_CH6"/>
        <enumValue label="PRS_CH7" value="PRS_CH7"/>
        <enumValue label="PRS_CH8" value="PRS_CH8"/>
        <enumValue label="PRS_CH9" value="PRS_CH9"/>
        <enumValue label="PRS_CH10" value="PRS_CH10"/>
        <enumValue label="PRS_CH11" value="PRS_CH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_CS" value="USART0_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_CS" value="USART1_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
        <enumValue label="TIMER1_CC3" value="TIMER1_CC3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_RAC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RAC_ACTIVE" value="RAC_ACTIVE"/>
        <enumValue label="RAC_TX" value="RAC_TX"/>
        <enumValue label="RAC_RX" value="RAC_RX"/>
        <enumValue label="RAC_LNAEN" value="RAC_LNAEN"/>
        <enumValue label="RAC_PAEN" value="RAC_PAEN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_PROTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PROTIMER_LBTS" value="PROTIMER_LBTS"/>
        <enumValue label="PROTIMER_LBTR" value="PROTIMER_LBTR"/>
        <enumValue label="PROTIMER_LBTF" value="PROTIMER_LBTF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_MODEM.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="MODEM_FRAMEDET" value="MODEM_FRAMEDET"/>
        <enumValue label="MODEM_PREDET" value="MODEM_PREDET"/>
        <enumValue label="MODEM_TIMDET" value="MODEM_TIMDET"/>
        <enumValue label="MODEM_FRAMESENT" value="MODEM_FRAMESENT"/>
        <enumValue label="MODEM_SYNCSENT" value="MODEM_SYNCSENT"/>
        <enumValue label="MODEM_PRESENT" value="MODEM_PRESENT"/>
        <enumValue label="MODEM_ANT0" value="MODEM_ANT0"/>
        <enumValue label="MODEM_ANT1" value="MODEM_ANT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_RFSENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RFSENSE_WU" value="RFSENSE_WU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_CRYOTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CRYOTIMER_PERIOD" value="CRYOTIMER_PERIOD"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH8_SIGNAL_CMU.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMU_CLKOUT0" value="CMU_CLKOUT0"/>
        <enumValue label="CMU_CLKOUT1" value="CMU_CLKOUT1"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch8_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH8.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH9.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH9_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="RAC" value="RAC"/>
        <enumValue label="PROTIMER" value="PROTIMER"/>
        <enumValue label="MODEM" value="MODEM"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="RFSENSE" value="RFSENSE"/>
        <enumValue label="CRYOTIMER" value="CRYOTIMER"/>
        <enumValue label="CMU" value="CMU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_CH0" value="PRS_CH0"/>
        <enumValue label="PRS_CH1" value="PRS_CH1"/>
        <enumValue label="PRS_CH2" value="PRS_CH2"/>
        <enumValue label="PRS_CH3" value="PRS_CH3"/>
        <enumValue label="PRS_CH4" value="PRS_CH4"/>
        <enumValue label="PRS_CH5" value="PRS_CH5"/>
        <enumValue label="PRS_CH6" value="PRS_CH6"/>
        <enumValue label="PRS_CH7" value="PRS_CH7"/>
        <enumValue label="PRS_CH8" value="PRS_CH8"/>
        <enumValue label="PRS_CH9" value="PRS_CH9"/>
        <enumValue label="PRS_CH10" value="PRS_CH10"/>
        <enumValue label="PRS_CH11" value="PRS_CH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_CS" value="USART0_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_CS" value="USART1_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
        <enumValue label="TIMER1_CC3" value="TIMER1_CC3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_RAC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RAC_ACTIVE" value="RAC_ACTIVE"/>
        <enumValue label="RAC_TX" value="RAC_TX"/>
        <enumValue label="RAC_RX" value="RAC_RX"/>
        <enumValue label="RAC_LNAEN" value="RAC_LNAEN"/>
        <enumValue label="RAC_PAEN" value="RAC_PAEN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_PROTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PROTIMER_LBTS" value="PROTIMER_LBTS"/>
        <enumValue label="PROTIMER_LBTR" value="PROTIMER_LBTR"/>
        <enumValue label="PROTIMER_LBTF" value="PROTIMER_LBTF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_MODEM.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="MODEM_FRAMEDET" value="MODEM_FRAMEDET"/>
        <enumValue label="MODEM_PREDET" value="MODEM_PREDET"/>
        <enumValue label="MODEM_TIMDET" value="MODEM_TIMDET"/>
        <enumValue label="MODEM_FRAMESENT" value="MODEM_FRAMESENT"/>
        <enumValue label="MODEM_SYNCSENT" value="MODEM_SYNCSENT"/>
        <enumValue label="MODEM_PRESENT" value="MODEM_PRESENT"/>
        <enumValue label="MODEM_ANT0" value="MODEM_ANT0"/>
        <enumValue label="MODEM_ANT1" value="MODEM_ANT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_RFSENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RFSENSE_WU" value="RFSENSE_WU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_CRYOTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CRYOTIMER_PERIOD" value="CRYOTIMER_PERIOD"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH9_SIGNAL_CMU.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMU_CLKOUT0" value="CMU_CLKOUT0"/>
        <enumValue label="CMU_CLKOUT1" value="CMU_CLKOUT1"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch9_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH9.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH10.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH10_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="RAC" value="RAC"/>
        <enumValue label="PROTIMER" value="PROTIMER"/>
        <enumValue label="MODEM" value="MODEM"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="RFSENSE" value="RFSENSE"/>
        <enumValue label="CRYOTIMER" value="CRYOTIMER"/>
        <enumValue label="CMU" value="CMU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_CH0" value="PRS_CH0"/>
        <enumValue label="PRS_CH1" value="PRS_CH1"/>
        <enumValue label="PRS_CH2" value="PRS_CH2"/>
        <enumValue label="PRS_CH3" value="PRS_CH3"/>
        <enumValue label="PRS_CH4" value="PRS_CH4"/>
        <enumValue label="PRS_CH5" value="PRS_CH5"/>
        <enumValue label="PRS_CH6" value="PRS_CH6"/>
        <enumValue label="PRS_CH7" value="PRS_CH7"/>
        <enumValue label="PRS_CH8" value="PRS_CH8"/>
        <enumValue label="PRS_CH9" value="PRS_CH9"/>
        <enumValue label="PRS_CH10" value="PRS_CH10"/>
        <enumValue label="PRS_CH11" value="PRS_CH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_CS" value="USART0_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_CS" value="USART1_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
        <enumValue label="TIMER1_CC3" value="TIMER1_CC3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_RAC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RAC_ACTIVE" value="RAC_ACTIVE"/>
        <enumValue label="RAC_TX" value="RAC_TX"/>
        <enumValue label="RAC_RX" value="RAC_RX"/>
        <enumValue label="RAC_LNAEN" value="RAC_LNAEN"/>
        <enumValue label="RAC_PAEN" value="RAC_PAEN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_PROTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PROTIMER_LBTS" value="PROTIMER_LBTS"/>
        <enumValue label="PROTIMER_LBTR" value="PROTIMER_LBTR"/>
        <enumValue label="PROTIMER_LBTF" value="PROTIMER_LBTF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_MODEM.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="MODEM_FRAMEDET" value="MODEM_FRAMEDET"/>
        <enumValue label="MODEM_PREDET" value="MODEM_PREDET"/>
        <enumValue label="MODEM_TIMDET" value="MODEM_TIMDET"/>
        <enumValue label="MODEM_FRAMESENT" value="MODEM_FRAMESENT"/>
        <enumValue label="MODEM_SYNCSENT" value="MODEM_SYNCSENT"/>
        <enumValue label="MODEM_PRESENT" value="MODEM_PRESENT"/>
        <enumValue label="MODEM_ANT0" value="MODEM_ANT0"/>
        <enumValue label="MODEM_ANT1" value="MODEM_ANT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_RFSENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RFSENSE_WU" value="RFSENSE_WU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_CRYOTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CRYOTIMER_PERIOD" value="CRYOTIMER_PERIOD"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH10_SIGNAL_CMU.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMU_CLKOUT0" value="CMU_CLKOUT0"/>
        <enumValue label="CMU_CLKOUT1" value="CMU_CLKOUT1"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch10_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH10.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <stringProperty label="Custom name" id="PRS.custom_name_CH11.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="Source" id="PRS.BSP_PRS_CH11_SOURCE.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
        <enumValue label="PRS" value="PRS"/>
        <enumValue label="ACMP0" value="ACMP0"/>
        <enumValue label="ACMP1" value="ACMP1"/>
        <enumValue label="ADC0" value="ADC0"/>
        <enumValue label="USART0" value="USART0"/>
        <enumValue label="USART1" value="USART1"/>
        <enumValue label="TIMER0" value="TIMER0"/>
        <enumValue label="TIMER1" value="TIMER1"/>
        <enumValue label="RAC" value="RAC"/>
        <enumValue label="PROTIMER" value="PROTIMER"/>
        <enumValue label="MODEM" value="MODEM"/>
        <enumValue label="RTCC" value="RTCC"/>
        <enumValue label="GPIO" value="GPIO"/>
        <enumValue label="LETIMER0" value="LETIMER0"/>
        <enumValue label="PCNT0" value="PCNT0"/>
        <enumValue label="RFSENSE" value="RFSENSE"/>
        <enumValue label="CRYOTIMER" value="CRYOTIMER"/>
        <enumValue label="CMU" value="CMU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_PRS.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PRS_CH0" value="PRS_CH0"/>
        <enumValue label="PRS_CH1" value="PRS_CH1"/>
        <enumValue label="PRS_CH2" value="PRS_CH2"/>
        <enumValue label="PRS_CH3" value="PRS_CH3"/>
        <enumValue label="PRS_CH4" value="PRS_CH4"/>
        <enumValue label="PRS_CH5" value="PRS_CH5"/>
        <enumValue label="PRS_CH6" value="PRS_CH6"/>
        <enumValue label="PRS_CH7" value="PRS_CH7"/>
        <enumValue label="PRS_CH8" value="PRS_CH8"/>
        <enumValue label="PRS_CH9" value="PRS_CH9"/>
        <enumValue label="PRS_CH10" value="PRS_CH10"/>
        <enumValue label="PRS_CH11" value="PRS_CH11"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_ACMP0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP0_OUT" value="ACMP0_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_ACMP1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ACMP1_OUT" value="ACMP1_OUT"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_ADC0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="ADC0_SINGLE" value="ADC0_SINGLE"/>
        <enumValue label="ADC0_SCAN" value="ADC0_SCAN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_USART0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART0_IRTX" value="USART0_IRTX"/>
        <enumValue label="USART0_TXC" value="USART0_TXC"/>
        <enumValue label="USART0_RXDATAV" value="USART0_RXDATAV"/>
        <enumValue label="USART0_RTS" value="USART0_RTS"/>
        <enumValue label="USART0_TX" value="USART0_TX"/>
        <enumValue label="USART0_CS" value="USART0_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_USART1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="USART1_TXC" value="USART1_TXC"/>
        <enumValue label="USART1_RXDATAV" value="USART1_RXDATAV"/>
        <enumValue label="USART1_RTS" value="USART1_RTS"/>
        <enumValue label="USART1_TX" value="USART1_TX"/>
        <enumValue label="USART1_CS" value="USART1_CS"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER0_UF" value="TIMER0_UF"/>
        <enumValue label="TIMER0_OF" value="TIMER0_OF"/>
        <enumValue label="TIMER0_CC0" value="TIMER0_CC0"/>
        <enumValue label="TIMER0_CC1" value="TIMER0_CC1"/>
        <enumValue label="TIMER0_CC2" value="TIMER0_CC2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_TIMER1.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="TIMER1_UF" value="TIMER1_UF"/>
        <enumValue label="TIMER1_OF" value="TIMER1_OF"/>
        <enumValue label="TIMER1_CC0" value="TIMER1_CC0"/>
        <enumValue label="TIMER1_CC1" value="TIMER1_CC1"/>
        <enumValue label="TIMER1_CC2" value="TIMER1_CC2"/>
        <enumValue label="TIMER1_CC3" value="TIMER1_CC3"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_RAC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RAC_ACTIVE" value="RAC_ACTIVE"/>
        <enumValue label="RAC_TX" value="RAC_TX"/>
        <enumValue label="RAC_RX" value="RAC_RX"/>
        <enumValue label="RAC_LNAEN" value="RAC_LNAEN"/>
        <enumValue label="RAC_PAEN" value="RAC_PAEN"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_PROTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PROTIMER_LBTS" value="PROTIMER_LBTS"/>
        <enumValue label="PROTIMER_LBTR" value="PROTIMER_LBTR"/>
        <enumValue label="PROTIMER_LBTF" value="PROTIMER_LBTF"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_MODEM.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="MODEM_FRAMEDET" value="MODEM_FRAMEDET"/>
        <enumValue label="MODEM_PREDET" value="MODEM_PREDET"/>
        <enumValue label="MODEM_TIMDET" value="MODEM_TIMDET"/>
        <enumValue label="MODEM_FRAMESENT" value="MODEM_FRAMESENT"/>
        <enumValue label="MODEM_SYNCSENT" value="MODEM_SYNCSENT"/>
        <enumValue label="MODEM_PRESENT" value="MODEM_PRESENT"/>
        <enumValue label="MODEM_ANT0" value="MODEM_ANT0"/>
        <enumValue label="MODEM_ANT1" value="MODEM_ANT1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_RTCC.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RTCC_CCV0" value="RTCC_CCV0"/>
        <enumValue label="RTCC_CCV1" value="RTCC_CCV1"/>
        <enumValue label="RTCC_CCV2" value="RTCC_CCV2"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_GPIO.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="GPIO_PIN0" value="GPIO_PIN0"/>
        <enumValue label="GPIO_PIN1" value="GPIO_PIN1"/>
        <enumValue label="GPIO_PIN2" value="GPIO_PIN2"/>
        <enumValue label="GPIO_PIN3" value="GPIO_PIN3"/>
        <enumValue label="GPIO_PIN4" value="GPIO_PIN4"/>
        <enumValue label="GPIO_PIN5" value="GPIO_PIN5"/>
        <enumValue label="GPIO_PIN6" value="GPIO_PIN6"/>
        <enumValue label="GPIO_PIN7" value="GPIO_PIN7"/>
        <enumValue label="GPIO_PIN8" value="GPIO_PIN8"/>
        <enumValue label="GPIO_PIN9" value="GPIO_PIN9"/>
        <enumValue label="GPIO_PIN10" value="GPIO_PIN10"/>
        <enumValue label="GPIO_PIN11" value="GPIO_PIN11"/>
        <enumValue label="GPIO_PIN12" value="GPIO_PIN12"/>
        <enumValue label="GPIO_PIN13" value="GPIO_PIN13"/>
        <enumValue label="GPIO_PIN14" value="GPIO_PIN14"/>
        <enumValue label="GPIO_PIN15" value="GPIO_PIN15"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_LETIMER0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="LETIMER0_CH0" value="LETIMER0_CH0"/>
        <enumValue label="LETIMER0_CH1" value="LETIMER0_CH1"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_PCNT0.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="PCNT0_TCC" value="PCNT0_TCC"/>
        <enumValue label="PCNT0_UFOF" value="PCNT0_UFOF"/>
        <enumValue label="PCNT0_DIR" value="PCNT0_DIR"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_RFSENSE.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="RFSENSE_WU" value="RFSENSE_WU"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_CRYOTIMER.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CRYOTIMER_PERIOD" value="CRYOTIMER_PERIOD"/>
      </enumProperty>
      <enumProperty label="Signal" id="PRS.BSP_PRS_CH11_SIGNAL_CMU.ENUM" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="CMU_CLKOUT0" value="CMU_CLKOUT0"/>
        <enumValue label="CMU_CLKOUT1" value="CMU_CLKOUT1"/>
      </enumProperty>
      <stringProperty label="Signal" id="PRS.bsp_prs_ch11_signal_disabled.STRING" defaultValue="" hidden="false" readonly="true"/>
      <enumProperty label="Output pin" id="PRS.BSP_PRS_CH11.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
    </properties>
    <propertyCategories>
      <category label="PRS">
        <subCategory label="">
          <propertyRef refId="PRS.usedbysdk.BOOL"/>
          <propertyRef refId="PRS.hiddenbysdk.BOOL"/>
          <propertyRef refId="PRS.showadvanced.BOOL"/>
          <propertyRef refId="PRS.forceenable.BOOL"/>
          <propertyRef refId="PRS.owner.STRING"/>
        </subCategory>
        <subCategory label="CH0 properties">
          <propertyRef refId="PRS.custom_name_CH0.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_RAC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_PROTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_MODEM.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_RFSENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_CRYOTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH0_SIGNAL_CMU.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch0_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH0.PIN"/>
        </subCategory>
        <subCategory label="CH1 properties">
          <propertyRef refId="PRS.custom_name_CH1.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_RAC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_PROTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_MODEM.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_RFSENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_CRYOTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH1_SIGNAL_CMU.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch1_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH1.PIN"/>
        </subCategory>
        <subCategory label="CH2 properties">
          <propertyRef refId="PRS.custom_name_CH2.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_RAC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_PROTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_MODEM.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_RFSENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_CRYOTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH2_SIGNAL_CMU.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch2_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH2.PIN"/>
        </subCategory>
        <subCategory label="CH3 properties">
          <propertyRef refId="PRS.custom_name_CH3.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_RAC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_PROTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_MODEM.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_RFSENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_CRYOTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH3_SIGNAL_CMU.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch3_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH3.PIN"/>
        </subCategory>
        <subCategory label="CH4 properties">
          <propertyRef refId="PRS.custom_name_CH4.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_RAC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_PROTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_MODEM.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_RFSENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_CRYOTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH4_SIGNAL_CMU.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch4_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH4.PIN"/>
        </subCategory>
        <subCategory label="CH5 properties">
          <propertyRef refId="PRS.custom_name_CH5.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_RAC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_PROTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_MODEM.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_RFSENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_CRYOTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH5_SIGNAL_CMU.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch5_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH5.PIN"/>
        </subCategory>
        <subCategory label="CH6 properties">
          <propertyRef refId="PRS.custom_name_CH6.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_RAC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_PROTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_MODEM.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_RFSENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_CRYOTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH6_SIGNAL_CMU.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch6_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH6.PIN"/>
        </subCategory>
        <subCategory label="CH7 properties">
          <propertyRef refId="PRS.custom_name_CH7.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_RAC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_PROTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_MODEM.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_RFSENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_CRYOTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH7_SIGNAL_CMU.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch7_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH7.PIN"/>
        </subCategory>
        <subCategory label="CH8 properties">
          <propertyRef refId="PRS.custom_name_CH8.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_RAC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_PROTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_MODEM.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_RFSENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_CRYOTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH8_SIGNAL_CMU.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch8_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH8.PIN"/>
        </subCategory>
        <subCategory label="CH9 properties">
          <propertyRef refId="PRS.custom_name_CH9.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_RAC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_PROTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_MODEM.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_RFSENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_CRYOTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH9_SIGNAL_CMU.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch9_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH9.PIN"/>
        </subCategory>
        <subCategory label="CH10 properties">
          <propertyRef refId="PRS.custom_name_CH10.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_RAC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_PROTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_MODEM.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_RFSENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_CRYOTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH10_SIGNAL_CMU.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch10_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH10.PIN"/>
        </subCategory>
        <subCategory label="CH11 properties">
          <propertyRef refId="PRS.custom_name_CH11.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SOURCE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_PRS.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_ACMP0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_ACMP1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_ADC0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_USART0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_USART1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_TIMER1.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_RAC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_PROTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_MODEM.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_RTCC.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_GPIO.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_LETIMER0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_PCNT0.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_RFSENSE.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_CRYOTIMER.ENUM"/>
          <propertyRef refId="PRS.BSP_PRS_CH11_SIGNAL_CMU.ENUM"/>
          <propertyRef refId="PRS.bsp_prs_ch11_signal_disabled.STRING"/>
          <propertyRef refId="PRS.BSP_PRS_CH11.PIN"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
