#!/bin/sh

# This file was generated by Simplicity Studio from the following template:
#   platform/bootloader/meta-inf/template/efr32/efr32-postbuild.sh
# Please do not edit it directly.

# Post Build processing for bootloader

DEVICE_SERIES_1=$--combineBootloader--$
if [ "${DEVICE_SERIES_1}" -eq 0 ]; then
  echo "Nothing to do in postbuild script"
  exit
fi

# use PATH_SCMD env var to override default path for Simplicity Commander
if [ -z "${PATH_SCMD}" ]; then
  COMMANDER="$--commanderPath--$"
  case `uname` in CYGWIN*) COMMANDER="`cygpath ${COMMANDER}`";; esac
else
  COMMANDER="${PATH_SCMD}/commander"
fi

if [ ! -f "${COMMANDER}" ]; then
  echo "Error: Simplicity Commander not found at '${COMMANDER}'"
  echo "Use PATH_SCMD env var to override default path for Simplicity Commander."
  exit
fi

FILENAME=$1


echo " "
echo "Add checksum to image (${FILENAME}-crc.s37)"
echo " "
"${COMMANDER}" convert "${FILENAME}.s37" --crc -o "${FILENAME}-crc.s37"


echo " "
echo "Add first stage bootloader to image (${FILENAME}-combined.s37)"
echo " "
"${COMMANDER}" convert "$--firstStageS37File--$" "${FILENAME}-crc.s37" -o "${FILENAME}-combined.s37"
