<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efm32.efm32gg11b.sdio" label="SDIO" name="SDIO" description="" version="efm">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="SDIO.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="SDIO.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="SDIO.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="SDIO.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="SDIO.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
    </properties>
    <propertyCategories>
      <category label="SDIO">
        <subCategory label="">
          <propertyRef refId="SDIO.usedbysdk.BOOL"/>
          <propertyRef refId="SDIO.hiddenbysdk.BOOL"/>
          <propertyRef refId="SDIO.showadvanced.BOOL"/>
          <propertyRef refId="SDIO.forceenable.BOOL"/>
          <propertyRef refId="SDIO.owner.STRING"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
