// This is an autogenerated config file, any changes to this file will be overwritten

#ifndef SLI_PSA_BUILTIN_CONFIG_AUTOGEN_H
#define SLI_PSA_BUILTIN_CONFIG_AUTOGEN_H

#define MBEDTLS_PSA_BUILTIN_KEY_TYPE_AES 1
#define MBEDTLS_PSA_BUILTIN_ALG_CMAC 1


#endif // SLI_PSA_BUILTIN_CONFIG_AUTOGEN_H
