<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efm32.efm32pg12b.adc0" label="ADC0" name="ADC0" description="" version="efm">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="ADC.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="ADC.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="ADC.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="ADC.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="ADC.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <stringProperty label="Custom name" id="ADC.customname.STRING" defaultValue="" hidden="false" readonly="false"/>
      <enumProperty label="mode" id="ADC.hal_adc_mode.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Single Channel Mode" value="single"/>
        <enumValue label="Scan Mode" value="scan"/>
      </enumProperty>
      <enumProperty label="Positive input selection" id="ADC.BSP_ADC_POS_INPUT.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="APORT bus ADC0X" value="APORT0X"/>
        <enumValue label="APORT bus AX" value="APORT1X"/>
        <enumValue label="APORT bus BX" value="APORT2X"/>
        <enumValue label="APORT bus CX" value="APORT3X"/>
        <enumValue label="APORT bus DX" value="APORT4X"/>
        <enumValue label="AVDD" value="AVDD"/>
        <enumValue label="DVDD" value="AREG"/>
        <enumValue label="DECOUPLE" value="PDBU"/>
        <enumValue label="IOVDD0" value="IO0"/>
        <enumValue label="TEMP" value="TEMP"/>
        <enumValue label="VSS" value="VSS"/>
      </enumProperty>
      <enumProperty label="Negative input selection" id="ADC.BSP_ADC_NEG_INPUT.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="APORT bus ADC0Y" value="APORT0Y"/>
        <enumValue label="APORT bus AY" value="APORT1Y"/>
        <enumValue label="APORT bus BY" value="APORT2Y"/>
        <enumValue label="APORT bus CY" value="APORT3Y"/>
        <enumValue label="APORT bus DY" value="APORT4Y"/>
        <enumValue label="VSS" value="VSS"/>
      </enumProperty>
      <integerProperty label="Scan input mask" id="ADC.BSP_ADC_SCAN_MASK.INT" minValue="0" maxValue="4294967295" defaultValue="0" hidden="false" readonly="true"/>
      <enumProperty label="Input 0 to 7" id="ADC.BSP_ADC_SCAN_INPUT0TO7.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="APORT bus ADC0 channel 0-7" value="APORT0CH0TO7"/>
        <enumValue label="APORT bus ADC0 channel 8-15 (no pins available)" value="APORT0CH8TO15"/>
        <enumValue label="APORT bus ADC0 channel 16-23 (no pins available)" value="APORT0CH16TO23"/>
        <enumValue label="APORT bus ADC0 channel 24-31 (no pins available)" value="APORT0CH24TO31"/>
        <enumValue label="APORT bus A channel 0-7" value="APORT1CH0TO7"/>
        <enumValue label="APORT bus A channel 8-15" value="APORT1CH8TO15"/>
        <enumValue label="APORT bus A channel 16-23" value="APORT1CH16TO23"/>
        <enumValue label="APORT bus A channel 24-31" value="APORT1CH24TO31"/>
        <enumValue label="APORT bus B channel 0-7" value="APORT2CH0TO7"/>
        <enumValue label="APORT bus B channel 8-15" value="APORT2CH8TO15"/>
        <enumValue label="APORT bus B channel 16-23" value="APORT2CH16TO23"/>
        <enumValue label="APORT bus B channel 24-31" value="APORT2CH24TO31"/>
        <enumValue label="APORT bus C channel 0-7" value="APORT3CH0TO7"/>
        <enumValue label="APORT bus C channel 8-15" value="APORT3CH8TO15"/>
        <enumValue label="APORT bus C channel 16-23" value="APORT3CH16TO23"/>
        <enumValue label="APORT bus C channel 24-31" value="APORT3CH24TO31"/>
        <enumValue label="APORT bus D channel 0-7" value="APORT4CH0TO7"/>
        <enumValue label="APORT bus D channel 8-15" value="APORT4CH8TO15"/>
        <enumValue label="APORT bus D channel 16-23" value="APORT4CH16TO23"/>
        <enumValue label="APORT bus D channel 24-31" value="APORT4CH24TO31"/>
      </enumProperty>
      <enumProperty label="Input 8 to 15" id="ADC.BSP_ADC_SCAN_INPUT8TO15.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="APORT bus ADC0 channel 0-7" value="APORT0CH0TO7"/>
        <enumValue label="APORT bus ADC0 channel 8-15 (no pins available)" value="APORT0CH8TO15"/>
        <enumValue label="APORT bus ADC0 channel 16-23 (no pins available)" value="APORT0CH16TO23"/>
        <enumValue label="APORT bus ADC0 channel 24-31 (no pins available)" value="APORT0CH24TO31"/>
        <enumValue label="APORT bus A channel 0-7" value="APORT1CH0TO7"/>
        <enumValue label="APORT bus A channel 8-15" value="APORT1CH8TO15"/>
        <enumValue label="APORT bus A channel 16-23" value="APORT1CH16TO23"/>
        <enumValue label="APORT bus A channel 24-31" value="APORT1CH24TO31"/>
        <enumValue label="APORT bus B channel 0-7" value="APORT2CH0TO7"/>
        <enumValue label="APORT bus B channel 8-15" value="APORT2CH8TO15"/>
        <enumValue label="APORT bus B channel 16-23" value="APORT2CH16TO23"/>
        <enumValue label="APORT bus B channel 24-31" value="APORT2CH24TO31"/>
        <enumValue label="APORT bus C channel 0-7" value="APORT3CH0TO7"/>
        <enumValue label="APORT bus C channel 8-15" value="APORT3CH8TO15"/>
        <enumValue label="APORT bus C channel 16-23" value="APORT3CH16TO23"/>
        <enumValue label="APORT bus C channel 24-31" value="APORT3CH24TO31"/>
        <enumValue label="APORT bus D channel 0-7" value="APORT4CH0TO7"/>
        <enumValue label="APORT bus D channel 8-15" value="APORT4CH8TO15"/>
        <enumValue label="APORT bus D channel 16-23" value="APORT4CH16TO23"/>
        <enumValue label="APORT bus D channel 24-31" value="APORT4CH24TO31"/>
      </enumProperty>
      <enumProperty label="Input 16 to 23" id="ADC.BSP_ADC_SCAN_INPUT16TO23.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="APORT bus ADC0 channel 0-7" value="APORT0CH0TO7"/>
        <enumValue label="APORT bus ADC0 channel 8-15 (no pins available)" value="APORT0CH8TO15"/>
        <enumValue label="APORT bus ADC0 channel 16-23 (no pins available)" value="APORT0CH16TO23"/>
        <enumValue label="APORT bus ADC0 channel 24-31 (no pins available)" value="APORT0CH24TO31"/>
        <enumValue label="APORT bus A channel 0-7" value="APORT1CH0TO7"/>
        <enumValue label="APORT bus A channel 8-15" value="APORT1CH8TO15"/>
        <enumValue label="APORT bus A channel 16-23" value="APORT1CH16TO23"/>
        <enumValue label="APORT bus A channel 24-31" value="APORT1CH24TO31"/>
        <enumValue label="APORT bus B channel 0-7" value="APORT2CH0TO7"/>
        <enumValue label="APORT bus B channel 8-15" value="APORT2CH8TO15"/>
        <enumValue label="APORT bus B channel 16-23" value="APORT2CH16TO23"/>
        <enumValue label="APORT bus B channel 24-31" value="APORT2CH24TO31"/>
        <enumValue label="APORT bus C channel 0-7" value="APORT3CH0TO7"/>
        <enumValue label="APORT bus C channel 8-15" value="APORT3CH8TO15"/>
        <enumValue label="APORT bus C channel 16-23" value="APORT3CH16TO23"/>
        <enumValue label="APORT bus C channel 24-31" value="APORT3CH24TO31"/>
        <enumValue label="APORT bus D channel 0-7" value="APORT4CH0TO7"/>
        <enumValue label="APORT bus D channel 8-15" value="APORT4CH8TO15"/>
        <enumValue label="APORT bus D channel 16-23" value="APORT4CH16TO23"/>
        <enumValue label="APORT bus D channel 24-31" value="APORT4CH24TO31"/>
      </enumProperty>
      <enumProperty label="Input 24 to 31" id="ADC.BSP_ADC_SCAN_INPUT24TO31.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="APORT bus ADC0 channel 0-7" value="APORT0CH0TO7"/>
        <enumValue label="APORT bus ADC0 channel 8-15 (no pins available)" value="APORT0CH8TO15"/>
        <enumValue label="APORT bus ADC0 channel 16-23 (no pins available)" value="APORT0CH16TO23"/>
        <enumValue label="APORT bus ADC0 channel 24-31 (no pins available)" value="APORT0CH24TO31"/>
        <enumValue label="APORT bus A channel 0-7" value="APORT1CH0TO7"/>
        <enumValue label="APORT bus A channel 8-15" value="APORT1CH8TO15"/>
        <enumValue label="APORT bus A channel 16-23" value="APORT1CH16TO23"/>
        <enumValue label="APORT bus A channel 24-31" value="APORT1CH24TO31"/>
        <enumValue label="APORT bus B channel 0-7" value="APORT2CH0TO7"/>
        <enumValue label="APORT bus B channel 8-15" value="APORT2CH8TO15"/>
        <enumValue label="APORT bus B channel 16-23" value="APORT2CH16TO23"/>
        <enumValue label="APORT bus B channel 24-31" value="APORT2CH24TO31"/>
        <enumValue label="APORT bus C channel 0-7" value="APORT3CH0TO7"/>
        <enumValue label="APORT bus C channel 8-15" value="APORT3CH8TO15"/>
        <enumValue label="APORT bus C channel 16-23" value="APORT3CH16TO23"/>
        <enumValue label="APORT bus C channel 24-31" value="APORT3CH24TO31"/>
        <enumValue label="APORT bus D channel 0-7" value="APORT4CH0TO7"/>
        <enumValue label="APORT bus D channel 8-15" value="APORT4CH8TO15"/>
        <enumValue label="APORT bus D channel 16-23" value="APORT4CH16TO23"/>
        <enumValue label="APORT bus D channel 24-31" value="APORT4CH24TO31"/>
      </enumProperty>
      <enumProperty label="Input 0" id="ADC.BSP_ADC_SCAN_INPUT0.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 1" id="ADC.BSP_ADC_SCAN_INPUT1.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 2" id="ADC.BSP_ADC_SCAN_INPUT2.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 3" id="ADC.BSP_ADC_SCAN_INPUT3.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 4" id="ADC.BSP_ADC_SCAN_INPUT4.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 5" id="ADC.BSP_ADC_SCAN_INPUT5.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 6" id="ADC.BSP_ADC_SCAN_INPUT6.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 7" id="ADC.BSP_ADC_SCAN_INPUT7.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 8" id="ADC.BSP_ADC_SCAN_INPUT8.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 9" id="ADC.BSP_ADC_SCAN_INPUT9.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 10" id="ADC.BSP_ADC_SCAN_INPUT10.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 11" id="ADC.BSP_ADC_SCAN_INPUT11.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 12" id="ADC.BSP_ADC_SCAN_INPUT12.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 13" id="ADC.BSP_ADC_SCAN_INPUT13.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 14" id="ADC.BSP_ADC_SCAN_INPUT14.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 15" id="ADC.BSP_ADC_SCAN_INPUT15.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 16" id="ADC.BSP_ADC_SCAN_INPUT16.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 17" id="ADC.BSP_ADC_SCAN_INPUT17.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 18" id="ADC.BSP_ADC_SCAN_INPUT18.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 19" id="ADC.BSP_ADC_SCAN_INPUT19.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 20" id="ADC.BSP_ADC_SCAN_INPUT20.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 21" id="ADC.BSP_ADC_SCAN_INPUT21.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 22" id="ADC.BSP_ADC_SCAN_INPUT22.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 23" id="ADC.BSP_ADC_SCAN_INPUT23.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 24" id="ADC.BSP_ADC_SCAN_INPUT24.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 25" id="ADC.BSP_ADC_SCAN_INPUT25.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 26" id="ADC.BSP_ADC_SCAN_INPUT26.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 27" id="ADC.BSP_ADC_SCAN_INPUT27.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 28" id="ADC.BSP_ADC_SCAN_INPUT28.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 29" id="ADC.BSP_ADC_SCAN_INPUT29.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 30" id="ADC.BSP_ADC_SCAN_INPUT30.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Input 31" id="ADC.BSP_ADC_SCAN_INPUT31.PIN" defaultValueIndex="0" hidden="false" readonly="true" transient="true">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Channel on APORT bus ADC0X (POS)" id="ADC.bsp_adc_pos_ADC0X.PIN" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Channel on APORT bus AX (POS)" id="ADC.bsp_adc_pos_AX.PIN" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Channel on APORT bus BX (POS)" id="ADC.bsp_adc_pos_BX.PIN" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Channel on APORT bus CX (POS)" id="ADC.bsp_adc_pos_CX.PIN" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Channel on APORT bus DX (POS)" id="ADC.bsp_adc_pos_DX.PIN" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Channel on APORT bus ADC0Y (NEG)" id="ADC.bsp_adc_neg_ADC0Y.PIN" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Channel on APORT bus AY (NEG)" id="ADC.bsp_adc_neg_AY.PIN" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Channel on APORT bus BY (NEG)" id="ADC.bsp_adc_neg_BY.PIN" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Channel on APORT bus CY (NEG)" id="ADC.bsp_adc_neg_CY.PIN" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="Channel on APORT bus DY (NEG)" id="ADC.bsp_adc_neg_DY.PIN" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <boolProperty label="Enable channel 0" id="ADC.bsp_adc_scan_ADC0_ch0.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 1" id="ADC.bsp_adc_scan_ADC0_ch1.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 2" id="ADC.bsp_adc_scan_ADC0_ch2.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 3" id="ADC.bsp_adc_scan_ADC0_ch3.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 0" id="ADC.bsp_adc_scan_A_ch0.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 1" id="ADC.bsp_adc_scan_A_ch1.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 2" id="ADC.bsp_adc_scan_A_ch2.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 3" id="ADC.bsp_adc_scan_A_ch3.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 4" id="ADC.bsp_adc_scan_A_ch4.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 5" id="ADC.bsp_adc_scan_A_ch5.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 6" id="ADC.bsp_adc_scan_A_ch6.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 7" id="ADC.bsp_adc_scan_A_ch7.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 8" id="ADC.bsp_adc_scan_A_ch8.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 9" id="ADC.bsp_adc_scan_A_ch9.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 10" id="ADC.bsp_adc_scan_A_ch10.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 11" id="ADC.bsp_adc_scan_A_ch11.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 16" id="ADC.bsp_adc_scan_A_ch16.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 17" id="ADC.bsp_adc_scan_A_ch17.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 18" id="ADC.bsp_adc_scan_A_ch18.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 19" id="ADC.bsp_adc_scan_A_ch19.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 20" id="ADC.bsp_adc_scan_A_ch20.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 21" id="ADC.bsp_adc_scan_A_ch21.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 22" id="ADC.bsp_adc_scan_A_ch22.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 23" id="ADC.bsp_adc_scan_A_ch23.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 24" id="ADC.bsp_adc_scan_A_ch24.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 25" id="ADC.bsp_adc_scan_A_ch25.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 26" id="ADC.bsp_adc_scan_A_ch26.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 27" id="ADC.bsp_adc_scan_A_ch27.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 28" id="ADC.bsp_adc_scan_A_ch28.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 29" id="ADC.bsp_adc_scan_A_ch29.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 30" id="ADC.bsp_adc_scan_A_ch30.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 31" id="ADC.bsp_adc_scan_A_ch31.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 0" id="ADC.bsp_adc_scan_B_ch0.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 1" id="ADC.bsp_adc_scan_B_ch1.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 2" id="ADC.bsp_adc_scan_B_ch2.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 3" id="ADC.bsp_adc_scan_B_ch3.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 4" id="ADC.bsp_adc_scan_B_ch4.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 5" id="ADC.bsp_adc_scan_B_ch5.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 6" id="ADC.bsp_adc_scan_B_ch6.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 7" id="ADC.bsp_adc_scan_B_ch7.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 8" id="ADC.bsp_adc_scan_B_ch8.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 9" id="ADC.bsp_adc_scan_B_ch9.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 10" id="ADC.bsp_adc_scan_B_ch10.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 11" id="ADC.bsp_adc_scan_B_ch11.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 16" id="ADC.bsp_adc_scan_B_ch16.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 17" id="ADC.bsp_adc_scan_B_ch17.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 18" id="ADC.bsp_adc_scan_B_ch18.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 19" id="ADC.bsp_adc_scan_B_ch19.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 20" id="ADC.bsp_adc_scan_B_ch20.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 21" id="ADC.bsp_adc_scan_B_ch21.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 22" id="ADC.bsp_adc_scan_B_ch22.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 23" id="ADC.bsp_adc_scan_B_ch23.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 24" id="ADC.bsp_adc_scan_B_ch24.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 25" id="ADC.bsp_adc_scan_B_ch25.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 26" id="ADC.bsp_adc_scan_B_ch26.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 27" id="ADC.bsp_adc_scan_B_ch27.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 28" id="ADC.bsp_adc_scan_B_ch28.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 29" id="ADC.bsp_adc_scan_B_ch29.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 30" id="ADC.bsp_adc_scan_B_ch30.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 31" id="ADC.bsp_adc_scan_B_ch31.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 0" id="ADC.bsp_adc_scan_C_ch0.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 1" id="ADC.bsp_adc_scan_C_ch1.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 2" id="ADC.bsp_adc_scan_C_ch2.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 3" id="ADC.bsp_adc_scan_C_ch3.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 4" id="ADC.bsp_adc_scan_C_ch4.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 5" id="ADC.bsp_adc_scan_C_ch5.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 6" id="ADC.bsp_adc_scan_C_ch6.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 7" id="ADC.bsp_adc_scan_C_ch7.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 8" id="ADC.bsp_adc_scan_C_ch8.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 9" id="ADC.bsp_adc_scan_C_ch9.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 10" id="ADC.bsp_adc_scan_C_ch10.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 11" id="ADC.bsp_adc_scan_C_ch11.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 12" id="ADC.bsp_adc_scan_C_ch12.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 13" id="ADC.bsp_adc_scan_C_ch13.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 14" id="ADC.bsp_adc_scan_C_ch14.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 15" id="ADC.bsp_adc_scan_C_ch15.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 22" id="ADC.bsp_adc_scan_C_ch22.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 23" id="ADC.bsp_adc_scan_C_ch23.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 24" id="ADC.bsp_adc_scan_C_ch24.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 25" id="ADC.bsp_adc_scan_C_ch25.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 26" id="ADC.bsp_adc_scan_C_ch26.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 27" id="ADC.bsp_adc_scan_C_ch27.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 28" id="ADC.bsp_adc_scan_C_ch28.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 29" id="ADC.bsp_adc_scan_C_ch29.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 30" id="ADC.bsp_adc_scan_C_ch30.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 31" id="ADC.bsp_adc_scan_C_ch31.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 0" id="ADC.bsp_adc_scan_D_ch0.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 1" id="ADC.bsp_adc_scan_D_ch1.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 2" id="ADC.bsp_adc_scan_D_ch2.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 3" id="ADC.bsp_adc_scan_D_ch3.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 4" id="ADC.bsp_adc_scan_D_ch4.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 5" id="ADC.bsp_adc_scan_D_ch5.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 6" id="ADC.bsp_adc_scan_D_ch6.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 7" id="ADC.bsp_adc_scan_D_ch7.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 8" id="ADC.bsp_adc_scan_D_ch8.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 9" id="ADC.bsp_adc_scan_D_ch9.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 10" id="ADC.bsp_adc_scan_D_ch10.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 11" id="ADC.bsp_adc_scan_D_ch11.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 12" id="ADC.bsp_adc_scan_D_ch12.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 13" id="ADC.bsp_adc_scan_D_ch13.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 14" id="ADC.bsp_adc_scan_D_ch14.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 15" id="ADC.bsp_adc_scan_D_ch15.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 22" id="ADC.bsp_adc_scan_D_ch22.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 23" id="ADC.bsp_adc_scan_D_ch23.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 24" id="ADC.bsp_adc_scan_D_ch24.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 25" id="ADC.bsp_adc_scan_D_ch25.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 26" id="ADC.bsp_adc_scan_D_ch26.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 27" id="ADC.bsp_adc_scan_D_ch27.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 28" id="ADC.bsp_adc_scan_D_ch28.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 29" id="ADC.bsp_adc_scan_D_ch29.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 30" id="ADC.bsp_adc_scan_D_ch30.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
      <boolProperty label="Enable channel 31" id="ADC.bsp_adc_scan_D_ch31.CHECKBOX" defaultValue="false" hidden="true" readonly="false"/>
    </properties>
    <propertyCategories>
      <category label="ADC0">
        <subCategory label="">
          <propertyRef refId="ADC.usedbysdk.BOOL"/>
          <propertyRef refId="ADC.hiddenbysdk.BOOL"/>
          <propertyRef refId="ADC.showadvanced.BOOL"/>
          <propertyRef refId="ADC.forceenable.BOOL"/>
          <propertyRef refId="ADC.owner.STRING"/>
          <propertyRef refId="ADC.customname.STRING"/>
          <propertyRef refId="ADC.hal_adc_mode.ENUM"/>
        </subCategory>
        <subCategory label="Single Channel Positive Input">
          <propertyRef refId="ADC.BSP_ADC_POS_INPUT.ENUM"/>
          <propertyRef refId="ADC.bsp_adc_pos_ADC0X.PIN"/>
          <propertyRef refId="ADC.bsp_adc_pos_AX.PIN"/>
          <propertyRef refId="ADC.bsp_adc_pos_BX.PIN"/>
          <propertyRef refId="ADC.bsp_adc_pos_CX.PIN"/>
          <propertyRef refId="ADC.bsp_adc_pos_DX.PIN"/>
        </subCategory>
        <subCategory label="Single Channel Negative Input">
          <propertyRef refId="ADC.BSP_ADC_NEG_INPUT.ENUM"/>
          <propertyRef refId="ADC.bsp_adc_neg_ADC0Y.PIN"/>
          <propertyRef refId="ADC.bsp_adc_neg_AY.PIN"/>
          <propertyRef refId="ADC.bsp_adc_neg_BY.PIN"/>
          <propertyRef refId="ADC.bsp_adc_neg_CY.PIN"/>
          <propertyRef refId="ADC.bsp_adc_neg_DY.PIN"/>
        </subCategory>
      </category>
      <category label="Scan Mode">
        <subCategory label="">
          <propertyRef refId="ADC.BSP_ADC_SCAN_MASK.INT"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT0TO7.ENUM"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT8TO15.ENUM"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT16TO23.ENUM"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT24TO31.ENUM"/>
        </subCategory>
        <subCategory label="APORT bus ADC0 channel 0-7">
          <propertyRef refId="ADC.bsp_adc_scan_ADC0_ch0.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_ADC0_ch1.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_ADC0_ch2.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_ADC0_ch3.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus A channel 0-7">
          <propertyRef refId="ADC.bsp_adc_scan_A_ch0.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch1.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch2.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch3.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch4.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch5.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch6.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch7.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus A channel 8-15">
          <propertyRef refId="ADC.bsp_adc_scan_A_ch8.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch9.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch10.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch11.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus A channel 16-23">
          <propertyRef refId="ADC.bsp_adc_scan_A_ch16.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch17.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch18.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch19.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch20.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch21.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch22.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch23.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus A channel 24-31">
          <propertyRef refId="ADC.bsp_adc_scan_A_ch24.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch25.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch26.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch27.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch28.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch29.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch30.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_A_ch31.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus B channel 0-7">
          <propertyRef refId="ADC.bsp_adc_scan_B_ch0.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch1.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch2.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch3.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch4.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch5.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch6.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch7.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus B channel 8-15">
          <propertyRef refId="ADC.bsp_adc_scan_B_ch8.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch9.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch10.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch11.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus B channel 16-23">
          <propertyRef refId="ADC.bsp_adc_scan_B_ch16.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch17.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch18.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch19.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch20.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch21.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch22.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch23.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus B channel 24-31">
          <propertyRef refId="ADC.bsp_adc_scan_B_ch24.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch25.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch26.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch27.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch28.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch29.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch30.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_B_ch31.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus C channel 0-7">
          <propertyRef refId="ADC.bsp_adc_scan_C_ch0.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch1.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch2.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch3.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch4.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch5.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch6.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch7.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus C channel 8-15">
          <propertyRef refId="ADC.bsp_adc_scan_C_ch8.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch9.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch10.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch11.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch12.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch13.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch14.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch15.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus C channel 16-23">
          <propertyRef refId="ADC.bsp_adc_scan_C_ch22.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch23.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus C channel 24-31">
          <propertyRef refId="ADC.bsp_adc_scan_C_ch24.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch25.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch26.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch27.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch28.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch29.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch30.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_C_ch31.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus D channel 0-7">
          <propertyRef refId="ADC.bsp_adc_scan_D_ch0.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch1.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch2.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch3.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch4.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch5.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch6.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch7.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus D channel 8-15">
          <propertyRef refId="ADC.bsp_adc_scan_D_ch8.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch9.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch10.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch11.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch12.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch13.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch14.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch15.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus D channel 16-23">
          <propertyRef refId="ADC.bsp_adc_scan_D_ch22.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch23.CHECKBOX"/>
        </subCategory>
        <subCategory label="APORT bus D channel 24-31">
          <propertyRef refId="ADC.bsp_adc_scan_D_ch24.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch25.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch26.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch27.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch28.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch29.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch30.CHECKBOX"/>
          <propertyRef refId="ADC.bsp_adc_scan_D_ch31.CHECKBOX"/>
        </subCategory>
      </category>
      <category label="Scan Mode Pinout">
        <subCategory label="">
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT0.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT1.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT2.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT3.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT4.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT5.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT6.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT7.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT8.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT9.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT10.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT11.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT12.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT13.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT14.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT15.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT16.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT17.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT18.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT19.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT20.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT21.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT22.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT23.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT24.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT25.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT26.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT27.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT28.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT29.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT30.PIN"/>
          <propertyRef refId="ADC.BSP_ADC_SCAN_INPUT31.PIN"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
