<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efm32.efm32tg11b.can0" label="CAN0" name="CAN0" description="" version="efm">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="CAN.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="CAN.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="CAN.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="CAN.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="CAN.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <stringProperty label="Custom name" id="CAN.customname.STRING" defaultValue="" hidden="false" readonly="false"/>
    </properties>
    <propertyCategories>
      <category label="CAN0">
        <subCategory label="">
          <propertyRef refId="CAN.usedbysdk.BOOL"/>
          <propertyRef refId="CAN.hiddenbysdk.BOOL"/>
          <propertyRef refId="CAN.showadvanced.BOOL"/>
          <propertyRef refId="CAN.forceenable.BOOL"/>
          <propertyRef refId="CAN.owner.STRING"/>
          <propertyRef refId="CAN.customname.STRING"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
