<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efm32.efm32pg12b.serial" label="SERIAL" name="SERIAL" description="" version="efm">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="SERIAL.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="SERIAL.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="SERIAL.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="SERIAL.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="SERIAL.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <enumProperty label="Port for application serial communication" description="Select the port on which application prints are communicated (such as printf())" id="SERIAL.BSP_SERIAL_APP_PORT.MOD" defaultValueIndex="0" hidden="false" readonly="false"/>
    </properties>
    <propertyCategories>
      <category label="SERIAL">
        <subCategory label="">
          <propertyRef refId="SERIAL.usedbysdk.BOOL"/>
          <propertyRef refId="SERIAL.hiddenbysdk.BOOL"/>
          <propertyRef refId="SERIAL.showadvanced.BOOL"/>
          <propertyRef refId="SERIAL.forceenable.BOOL"/>
          <propertyRef refId="SERIAL.owner.STRING"/>
          <propertyRef refId="SERIAL.BSP_SERIAL_APP_PORT.MOD"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
