<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efr32.efr32mg13p.leuart0" label="LEUART0" name="LEUART0" description="Low-Energy UART" version="efr">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="LEUART.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="LEUART.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="LEUART.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="LEUART.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="LEUART.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <stringProperty label="Custom name" id="LEUART.customname.STRING" defaultValue="" hidden="false" readonly="false"/>
      <integerProperty label="Baud rate" description="Specify the baud rate of the LEUART. Must be less than refFreq/oversampling as described in the reference manual" id="LEUART.HAL_LEUART_BAUD_RATE.INT" minValue="1" maxValue="10000000" defaultValue="9600" hidden="false" readonly="false"/>
      <enumProperty label="Flow control mode" description="Configure flow control for the LEUART" id="LEUART.HAL_LEUART_FLOW_CONTROL.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="No flow control" value="HAL_LEUART_FLOW_CONTROL_NONE"/>
        <enumValue label="Xon-Xoff" value="HAL_LEUART_FLOW_CONTROL_SW"/>
        <enumValue label="GPIO-based CTS/RTS" value="HAL_LEUART_FLOW_CONTROL_HW"/>
      </enumProperty>
      <integerProperty label="Flow control threshold" description="Flow control assert threshold (flow control is asserted once less than the specified amount of bytes are available in the RX buffer)" id="LEUART.HAL_LEUART_RXSTOP.INT" minValue="0" maxValue="65535" defaultValue="0" hidden="true" readonly="false"/>
      <integerProperty label="Release flow control threshold" description="Flow control release threshold (flow control is released once more than the specified amount of bytes are available in the RX buffer). Must be a multiple of the assert flow control threshold" id="LEUART.HAL_LEUART_RXSTART.INT" minValue="0" maxValue="65535" defaultValue="0" hidden="true" readonly="false"/>
      <integerProperty label="TX buffer size" description="Transmit buffer size" id="LEUART.HAL_LEUART_TX_QUEUE_SIZE.INT" minValue="0" maxValue="65535" defaultValue="0" hidden="true" readonly="false"/>
      <integerProperty label="RX buffer size" description="Receive buffer size. Must be a multiple of the assert flow control threshold" id="LEUART.HAL_LEUART_RX_QUEUE_SIZE.INT" minValue="0" maxValue="65535" defaultValue="0" hidden="true" readonly="false"/>
      <enumProperty label="TX pin" description="Select pin for the TX signal" id="LEUART.BSP_LEUART_TX.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="RX pin" description="Select pin for the RX signal" id="LEUART.BSP_LEUART_RX.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
    </properties>
    <propertyCategories>
      <category label="LEUART0">
        <subCategory label="">
          <propertyRef refId="LEUART.usedbysdk.BOOL"/>
          <propertyRef refId="LEUART.hiddenbysdk.BOOL"/>
          <propertyRef refId="LEUART.showadvanced.BOOL"/>
          <propertyRef refId="LEUART.forceenable.BOOL"/>
          <propertyRef refId="LEUART.owner.STRING"/>
          <propertyRef refId="LEUART.customname.STRING"/>
          <propertyRef refId="LEUART.HAL_LEUART_BAUD_RATE.INT"/>
          <propertyRef refId="LEUART.HAL_LEUART_FLOW_CONTROL.ENUM"/>
          <propertyRef refId="LEUART.HAL_LEUART_RXSTOP.INT"/>
          <propertyRef refId="LEUART.HAL_LEUART_RXSTART.INT"/>
          <propertyRef refId="LEUART.HAL_LEUART_TX_QUEUE_SIZE.INT"/>
          <propertyRef refId="LEUART.HAL_LEUART_RX_QUEUE_SIZE.INT"/>
          <propertyRef refId="LEUART.BSP_LEUART_TX.PIN"/>
          <propertyRef refId="LEUART.BSP_LEUART_RX.PIN"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
