<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module description="" id="efm32.efm32zg.port" label="Port" name="Port" version="A">
    <properties>

    </properties>
    <propertyCategories>
      <category label="Port Bank">
        <subCategory label="Settings">

        </subCategory>
      </category>
    </propertyCategories>
  </module>
</module:DocumentRoot>