<?xml version='1.0' encoding='ASCII'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="efr32.efr32fg22.euart0" label="EUART0" name="EUART0" description="EUART" version="efr">
    <properties>
      <enumProperty label="SDK is taking control over this module" id="EUART.usedbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="SDK is hiding this module" id="EUART.hiddenbysdk.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Show advanced options" id="EUART.showadvanced.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <enumProperty label="Forcefully enabled in model" id="EUART.forceenable.BOOL" defaultValueIndex="0" hidden="true" readonly="false">
        <enumValue label="False" value="0"/>
        <enumValue label="True" value="1"/>
      </enumProperty>
      <stringProperty label="Owned by" id="EUART.owner.STRING" defaultValue="" hidden="false" readonly="true" transient="true"/>
      <stringProperty label="Custom name" id="EUART.customname.STRING" defaultValue="" hidden="false" readonly="false"/>
      <integerProperty label="Baud rate" description="Specify the baud rate of the UART. Must be less than refFreq/oversampling as described in the reference manual" id="EUART.HAL_EUART_BAUD_RATE.INT" minValue="1" maxValue="4294967295" defaultValue="115200" hidden="false" readonly="false"/>
      <enumProperty label="Flow control mode" description="Configure flow control for the UART" id="EUART.HAL_EUART_FLOW_CONTROL.ENUM" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="No flow control" value="HAL_UART_FLOW_CONTROL_NONE"/>
        <enumValue label="Xon-Xoff" value="HAL_UART_FLOW_CONTROL_SW"/>
        <enumValue label="GPIO-based CTS/RTS" value="HAL_UART_FLOW_CONTROL_HW"/>
        <enumValue label="USART-based CTS/RTS" value="HAL_UART_FLOW_CONTROL_HWUART"/>
      </enumProperty>
      <integerProperty label="Flow control threshold" description="Flow control assert threshold (flow control is asserted once less than the specified amount of bytes are available in the RX buffer)" id="EUART.HAL_UART_RXSTOP.INT" minValue="0" maxValue="65535" defaultValue="0" hidden="true" readonly="false"/>
      <integerProperty label="Release flow control threshold" description="Flow control release threshold (flow control is released once more than the specified amount of bytes are available in the RX buffer). Must be a multiple of the assert flow control threshold" id="EUART.HAL_UART_RXSTART.INT" minValue="0" maxValue="65535" defaultValue="0" hidden="true" readonly="false"/>
      <integerProperty label="TX buffer size" description="Transmit buffer size." id="EUART.HAL_UART_TX_QUEUE_SIZE.INT" minValue="0" maxValue="65535" defaultValue="0" hidden="true" readonly="false"/>
      <integerProperty label="RX buffer size" description="Receive buffer size. Must be a multiple of the assert flow control threshold" id="EUART.HAL_UART_RX_QUEUE_SIZE.INT" minValue="0" maxValue="65535" defaultValue="0" hidden="true" readonly="false"/>
      <enumProperty label="TX pin" description="Select pin for the TX signal" id="EUART.BSP_EUART_TX.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="RX pin" description="Select pin for the RX signal" id="EUART.BSP_EUART_RX.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="CTS pin" description="Select pin for the CTS signal" id="EUART.BSP_EUART_CTS.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
      <enumProperty label="RTS pin" description="Select pin for the RTS signal" id="EUART.BSP_EUART_RTS.PIN" defaultValueIndex="0" hidden="false" readonly="false">
        <enumValue label="Disabled" value="Disabled"/>
      </enumProperty>
    </properties>
    <propertyCategories>
      <category label="EUART0">
        <subCategory label="">
          <propertyRef refId="EUART.usedbysdk.BOOL"/>
          <propertyRef refId="EUART.hiddenbysdk.BOOL"/>
          <propertyRef refId="EUART.showadvanced.BOOL"/>
          <propertyRef refId="EUART.forceenable.BOOL"/>
          <propertyRef refId="EUART.owner.STRING"/>
          <propertyRef refId="EUART.customname.STRING"/>
          <propertyRef refId="EUART.HAL_EUART_BAUD_RATE.INT"/>
          <propertyRef refId="EUART.HAL_EUART_FLOW_CONTROL.ENUM"/>
          <propertyRef refId="EUART.HAL_UART_RXSTOP.INT"/>
          <propertyRef refId="EUART.HAL_UART_RXSTART.INT"/>
          <propertyRef refId="EUART.HAL_UART_TX_QUEUE_SIZE.INT"/>
          <propertyRef refId="EUART.HAL_UART_RX_QUEUE_SIZE.INT"/>
          <propertyRef refId="EUART.BSP_EUART_TX.PIN"/>
          <propertyRef refId="EUART.BSP_EUART_RX.PIN"/>
          <propertyRef refId="EUART.BSP_EUART_CTS.PIN"/>
          <propertyRef refId="EUART.BSP_EUART_RTS.PIN"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals/>
  </module>
</module:DocumentRoot>
